(function () {
  const { EvolutionLab, NeuralGenome, DEFAULT_SEED_TEXT, CHAT_PRIMER_TEXT, CONTROL_HUMAN, CONTROL_ASSISTANT, CONTROL_TURN_END, MAX_NEURONS, MAX_SYNAPSES, DEFAULT_VOCAB_SIZE, clamp, cleanGeneratedText, chatQualityScore } = window.GenesisEngine;

  const el = id => document.getElementById(id);
  const state = {
    lab: new EvolutionLab(),
    evolving: false,
    imageTargets: [],
    lastImageTarget: null,
    lastCycleAt: 0,
    backgroundWorker: null,
    workerBusy: false,
    ws: null,
    serverChatAvailable: false,
    topologyActive: false,
    topologyRaf: 0,
    topologyLastDraw: 0,
    lastActivityAt: 0,
    cachedActivity: null,
    statusTimer: 0
  };
  const MAX_IMPORTED_TEXT_CHARS = 1_200_000;

  function safeChatText(text, fallback = "I am still stabilizing my chat vocabulary. Try a little more text training, then ask again.") {
    const cleaned = cleanGeneratedText(String(text || ""), 2400);
    return cleaned && chatQualityScore(cleaned) >= 0.55 ? cleaned : fallback;
  }

  function chatFallbackFor(prompt) {
    return /^(hi|hey|hello|yo|sup)[\s!.?]*$/i.test(prompt || "")
      ? "Hey. I am awake. My chat vocabulary is cleaned up now, and I am still learning from the local organism."
      : "I am still stabilizing my chat vocabulary. Try a little more text training, then ask again.";
  }

  const views = {
    train: {
      title: "Training Console",
      subtitle: "Import real text and images, then evolve a local sparse neural organism."
    },
    chat: {
      title: "Chat Mode",
      subtitle: "A subword-token sparse organism generated by this app, not an external AI service."
    },
    image: {
      title: "Image Mode",
      subtitle: "A local neural pattern generator that can evolve toward imported visual targets."
    },
    network: {
      title: "Network Compute",
      subtitle: "Use browser tabs and LAN devices you control to search for stronger genomes."
    }
  };

  function log(message) {
    const line = `[${new Date().toLocaleTimeString()}] ${message}`;
    el("trainingLog").textContent = `${line}\n${el("trainingLog").textContent}`.slice(0, 8000);
  }

  function setStatus(message) {
    el("statusPill").textContent = message;
  }

  function setToolStatus(message) {
    if (el("toolStatus")) el("toolStatus").textContent = message;
  }

  function serializableImageTarget(target) {
    if (!target) return null;
    return {
      name: target.name || "image target",
      size: target.size || 48,
      pixels: Array.from(target.pixels || [])
    };
  }

  function saveBrowserCheckpoint(reason = "checkpoint") {
    try {
      const checkpoint = {
        format: "genesis-lab-browser-checkpoint-v1",
        reason,
        savedAt: new Date().toISOString(),
        corpus: state.lab.corpus,
        corpora: state.lab.corpora,
        persistentContext: state.lab.persistentContext,
        memoryBank: state.lab.memoryBank,
        curriculumLevel: state.lab.curriculumLevel,
        imageTargets: state.imageTargets.map(serializableImageTarget).filter(Boolean),
        config: state.lab.config,
        generation: state.lab.generation,
        champion: state.lab.best().toJSON()
      };
      localStorage.setItem("genesis-lab-last-safe-checkpoint", JSON.stringify(checkpoint));
      return true;
    } catch (error) {
      log(`Checkpoint skipped: ${error.message}`);
      return false;
    }
  }

  function readConfig() {
    return {
      neurons: clamp(Number(el("neuronInput").value) || 400, 64, MAX_NEURONS),
      synapses: clamp(Number(el("synapseInput").value) || 1400, 128, MAX_SYNAPSES),
      populationSize: clamp(Number(el("populationInput").value) || 10, 4, 24),
      mutation: clamp(Number(el("mutationInput").value) || 0.035, 0.001, 0.2),
      scalarMutation: state.lab?.config?.scalarMutation ?? 0.028,
      vocabSize: state.lab?.config?.vocabSize ?? DEFAULT_VOCAB_SIZE,
      gradientSteps: state.lab?.config?.gradientSteps ?? 2,
      gradientLearningRate: state.lab?.config?.gradientLearningRate ?? 0.016
    };
  }

  function syncConfigToLab() {
    state.lab.setConfig(readConfig());
    if (state.lab.corpora.length <= 1) state.lab.setCorpus(el("corpusText").value);
  }

  function formatChars(count) {
    if (count > 1_000_000) return `${(count / 1_000_000).toFixed(1)}m`;
    if (count > 1_000) return `${(count / 1_000).toFixed(1)}k`;
    return String(count);
  }

  function updateReadout() {
    const best = state.lab.best();
    const now = performance.now();
    const activityPrompt = el("chatPrompt")?.value || el("corpusText")?.value || "";
    if (!state.cachedActivity || now - state.lastActivityAt > (state.evolving ? 900 : 350)) {
      state.cachedActivity = best?.getActivity(activityPrompt);
      state.lastActivityAt = now;
    }
    const activity = state.cachedActivity;
    const neuronCounts = state.lab.population.map(genome => genome.neurons);
    const synapseCounts = state.lab.population.map(genome => genome.synapses);
    const topology = {
      bestNeurons: best?.neurons || 0,
      minNeurons: neuronCounts.length ? Math.min(...neuronCounts) : 0,
      maxNeurons: neuronCounts.length ? Math.max(...neuronCounts) : 0,
      avgNeurons: neuronCounts.length ? Math.round(neuronCounts.reduce((sum, value) => sum + value, 0) / neuronCounts.length) : 0,
      bestSynapses: best?.synapses || 0,
      minSynapses: synapseCounts.length ? Math.min(...synapseCounts) : 0,
      maxSynapses: synapseCounts.length ? Math.max(...synapseCounts) : 0,
      avgSynapses: synapseCounts.length ? Math.round(synapseCounts.reduce((sum, value) => sum + value, 0) / synapseCounts.length) : 0
    };
    el("generationLabel").textContent = `Gen ${state.lab.generation}`;
    el("fitnessStat").textContent = (best?.fitness || 0).toFixed(3);
    el("corpusStat").textContent = `${formatChars(state.lab.corpus.length)} chars`;
    el("vocabStat").textContent = String(state.lab.vocab.length);
    el("lossMetric").textContent = Number.isFinite(best?.loss) && best.loss < 900 ? best.loss.toFixed(3) : "--";
    el("fitnessStat").textContent = (best?.fitness || 0).toFixed(3);
    el("speciesMetric").textContent = best ? `${topology.bestNeurons}n best / ${topology.maxNeurons}n max` : "--";
    el("cycleMetric").textContent = state.lab.history.length ? `${state.lab.history.at(-1).elapsed}ms` : "--";
    el("neuronInput").value = state.lab.config.neurons;
    el("synapseInput").value = state.lab.config.synapses;
    el("populationInput").value = state.lab.config.populationSize;
    el("modelReadout").textContent = JSON.stringify({
      generation: state.lab.generation,
      neurons: best?.neurons,
      synapses: best?.synapses,
      population: state.lab.population.length,
      topology,
      vocab: state.lab.vocab.length,
      fitness: best?.fitness,
      loss: best?.loss,
      corpusChars: state.lab.corpus.length,
      imageTargets: state.imageTargets.length,
      visualTrainingActive: state.imageTargets.length > 0,
      corpora: state.lab.corpora.length,
      curriculumLevel: state.lab.curriculumLevel,
      species: state.lab.species.length,
      personality: Array.from(best?.personality || []).slice(0, 6).map(value => Number(value.toFixed(3))),
      maxNeuronLimit: MAX_NEURONS,
      maxSynapseLimit: MAX_SYNAPSES,
      externalAI: false
    }, null, 2);
    if (el("personalityReadout")) {
      el("personalityReadout").textContent = `personality ${Array.from(best?.personality || []).slice(0, 8).map(value => value.toFixed(2)).join(" ")}`;
    }
    if (el("imageReadout")) {
      el("imageReadout").textContent = JSON.stringify({
        visualMemory: Array.from(best?.visualMemory || []).slice(0, 8).map(value => Number(value.toFixed(3))),
        targets: state.imageTargets.length,
        lastImageLoss: state.lab.lastImageLoss == null ? null : Number(state.lab.lastImageLoss.toFixed(5)),
        activeTarget: state.lastImageTarget?.name || null,
        autoencoder: "visual-latent trainImage active"
      }, null, 2);
    }
    drawFitness();
    drawActivity(activity);
  }

  function drawFitness() {
    const canvas = el("fitnessCanvas");
    const ctx = canvas.getContext("2d");
    const width = canvas.width;
    const height = canvas.height;
    ctx.clearRect(0, 0, width, height);
    ctx.fillStyle = "#050805";
    ctx.fillRect(0, 0, width, height);
    ctx.strokeStyle = "rgba(244, 240, 223, 0.08)";
    ctx.lineWidth = 1;
    for (let i = 1; i < 5; i++) {
      const y = (height / 5) * i;
      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(width, y);
      ctx.stroke();
    }

    const points = state.lab.history;
    if (points.length < 2) return;
    const max = Math.max(...points.map(point => point.fitness), 0.001);
    ctx.strokeStyle = "#b9f26d";
    ctx.lineWidth = 3;
    ctx.beginPath();
    points.forEach((point, index) => {
      const x = (index / (points.length - 1)) * width;
      const y = height - (point.fitness / max) * (height - 20) - 10;
      if (index === 0) ctx.moveTo(x, y);
      else ctx.lineTo(x, y);
    });
    ctx.stroke();
  }

  function resetFitnessGraph() {
    state.lab.history = [];
    drawFitness();
    updateReadout();
    log("Fitness graph reset. Champion, population, training data, and server model were left unchanged.");
  }

  function drawActivity(activity) {
    const canvas = el("activityCanvas");
    if (!canvas || !activity) return;
    const ctx = canvas.getContext("2d");
    const width = canvas.width;
    const height = canvas.height;
    ctx.clearRect(0, 0, width, height);
    ctx.fillStyle = "#050805";
    ctx.fillRect(0, 0, width, height);
    const buckets = activity.buckets || [];
    const cell = width / Math.max(1, buckets.length);
    for (let i = 0; i < buckets.length; i++) {
      const value = buckets[i];
      const hue = 88 + value * 90;
      ctx.fillStyle = `hsl(${hue} 80% ${24 + value * 48}%)`;
      ctx.fillRect(i * cell, height - value * height, Math.max(1, cell - 1), value * height);
    }
    ctx.fillStyle = "rgba(244, 240, 223, 0.72)";
    ctx.font = "12px Consolas, monospace";
    ctx.fillText(`memory gates: ${activity.memory.slice(0, 6).map(value => value.toFixed(2)).join(" ")}`, 12, 18);
    ctx.fillText(`species: ${activity.speciesId}`, 12, 36);
  }

  function topologyPosition(node, index, count, width, height, tick) {
    const centerX = width / 2;
    const centerY = height / 2;
    const type = node.type || 0;
    const ring = type === 3 ? 0.36 : type === 4 ? 0.54 : type === 5 ? 0.68 : type === 1 ? 0.46 : type === 2 ? 0.58 : 0.74;
    const golden = 2.399963229728653;
    const angle = (node.id * golden + tick * (type === 2 ? 0.0007 : 0.00025)) % (Math.PI * 2);
    const wobble = Math.sin(node.id * 0.13 + tick * 0.001) * 0.035;
    const radius = Math.min(width, height) * (ring + wobble) * 0.46;
    return {
      x: centerX + Math.cos(angle) * radius,
      y: centerY + Math.sin(angle) * radius
    };
  }

  function drawTopologyFrame(now = performance.now()) {
    if (!state.topologyActive) return;
    state.topologyRaf = requestAnimationFrame(drawTopologyFrame);
    if (now - state.topologyLastDraw < 90) return;
    state.topologyLastDraw = now;

    const canvas = el("topologyCanvas");
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    const width = canvas.width;
    const height = canvas.height;
    const prompt = el("chatPrompt")?.value || el("corpusText")?.value || "";
    const view = state.lab.best().topologyView(prompt, 280, 780);
    const positions = new Map();

    ctx.clearRect(0, 0, width, height);
    ctx.fillStyle = "rgba(3, 6, 4, 0.62)";
    ctx.fillRect(0, 0, width, height);
    ctx.strokeStyle = "rgba(244, 240, 223, 0.08)";
    ctx.lineWidth = 1;
    for (let r = 0.18; r <= 0.82; r += 0.16) {
      ctx.beginPath();
      ctx.ellipse(width / 2, height / 2, width * r * 0.48, height * r * 0.48, 0, 0, Math.PI * 2);
      ctx.stroke();
    }

    view.nodes.forEach((node, index) => {
      positions.set(node.id, topologyPosition(node, index, view.nodes.length, width, height, now));
    });

    for (const edge of view.edges) {
      const from = positions.get(edge.from);
      const to = positions.get(edge.to);
      if (!from || !to) continue;
      const pulse = clamp(edge.firing, 0, 1);
      ctx.strokeStyle = edge.weight >= 0
        ? `rgba(185, 242, 109, ${0.045 + pulse * 0.42})`
        : `rgba(255, 111, 97, ${0.045 + pulse * 0.38})`;
      ctx.lineWidth = 0.45 + pulse * 2.4;
      ctx.beginPath();
      ctx.moveTo(from.x, from.y);
      const midX = (from.x + to.x) / 2 + Math.sin(edge.from + edge.to) * 18;
      const midY = (from.y + to.y) / 2 + Math.cos(edge.from - edge.to) * 18;
      ctx.quadraticCurveTo(midX, midY, to.x, to.y);
      ctx.stroke();
    }

    for (const node of view.nodes) {
      const point = positions.get(node.id);
      const activity = Math.min(1, Math.abs(node.activity));
      const radius = 2.8 + activity * 7.2 + (node.type === 4 ? 1.4 : 0);
      ctx.fillStyle = node.color;
      ctx.globalAlpha = 0.42 + activity * 0.58;
      ctx.beginPath();
      ctx.arc(point.x, point.y, radius, 0, Math.PI * 2);
      ctx.fill();
      if (activity > 0.32) {
        ctx.strokeStyle = node.color;
        ctx.globalAlpha = 0.2 + activity * 0.35;
        ctx.lineWidth = 1.2;
        ctx.beginPath();
        ctx.arc(point.x, point.y, radius + 5 + Math.sin(now * 0.006 + node.id) * 2, 0, Math.PI * 2);
        ctx.stroke();
      }
    }
    ctx.globalAlpha = 1;
    ctx.fillStyle = "rgba(244, 240, 223, 0.82)";
    ctx.font = "13px Consolas, monospace";
    ctx.fillText(`${view.neurons.toLocaleString()} neurons / ${view.synapses.toLocaleString()} synapses / ${view.edges.length} visible firing paths`, 16, 24);
    let x = 16;
    for (const type of view.types) {
      ctx.fillStyle = type.color;
      ctx.fillRect(x, height - 24, 10, 10);
      ctx.fillStyle = "rgba(244, 240, 223, 0.72)";
      ctx.fillText(type.name, x + 14, height - 15);
      x += 92;
    }
    if (el("topologyStatus")) el("topologyStatus").textContent = `${view.nodes.length} cells sampled, ${view.edges.length} connections firing`;
  }

  function toggleTopologyView() {
    state.topologyActive = !state.topologyActive;
    const canvas = el("topologyCanvas");
    if (canvas) canvas.hidden = !state.topologyActive;
    el("topologyButton").textContent = state.topologyActive ? "Hide topology" : "Top-down topology";
    if (state.topologyActive) {
      if (location.hash !== "#topology") history.replaceState(null, "", "#topology");
      log("Top-down topology view active: biologically inspired excitatory, inhibitory, modulatory, sensory, memory, and visual cells.");
      drawTopologyFrame();
    } else {
      if (location.hash === "#topology") history.replaceState(null, "", location.pathname + location.search);
      cancelAnimationFrame(state.topologyRaf);
      state.topologyRaf = 0;
      if (el("topologyStatus")) el("topologyStatus").textContent = "idle";
    }
  }

  function switchView(name) {
    document.querySelectorAll(".mode-button").forEach(button => {
      button.classList.toggle("active", button.dataset.view === name);
    });
    document.querySelectorAll(".view").forEach(view => view.classList.remove("active"));
    el(`${name}View`).classList.add("active");
    el("viewTitle").textContent = views[name].title;
    el("viewSubtitle").textContent = views[name].subtitle;
  }

  async function evolveStep(imageOptions = {}) {
    syncConfigToLab();
    const imageTargets = state.imageTargets.length ? state.imageTargets : [];
    if (state.backgroundWorker && !imageOptions.forceMainThread) {
      return evolveStepInWorker(imageOptions);
    }
    const result = state.lab.evolveOnce({
      imageTarget: imageOptions.imageTarget || null,
      imageTargets,
      imagePrompt: imageOptions.imagePrompt || el("imagePrompt").value,
      imageLearningRate: Number(el("imageMutation")?.value || 0.012) * 0.5,
      maxChars: Number(state.lab.config.neurons) > 1800 ? 420 : 760
    });
    if (result.imageTarget) state.lastImageTarget = result.imageTarget;
    state.lastCycleAt = Date.now();
    const maxNeurons = Math.max(...state.lab.population.map(genome => genome.neurons));
    const minNeurons = Math.min(...state.lab.population.map(genome => genome.neurons));
    const maxSynapses = Math.max(...state.lab.population.map(genome => genome.synapses));
    const minSynapses = Math.min(...state.lab.population.map(genome => genome.synapses));
    const imageNote = result.imageTarget ? `, image "${result.imageTarget.name}" loss ${Number(result.imageLoss).toFixed(4)}` : "";
    log(`Generation ${state.lab.generation}: fitness ${result.best.fitness.toFixed(4)}, loss ${result.best.loss.toFixed(3)}, best ${result.best.neurons}n/${result.best.synapses}s, population ${minNeurons}-${maxNeurons}n and ${minSynapses}-${maxSynapses}s${imageNote}.`);
    updateReadout();
    return result;
  }

  function evolveStepInWorker(imageOptions = {}) {
    if (state.workerBusy) return Promise.resolve({ best: state.lab.best(), elapsed: 0, queued: true });
    state.workerBusy = true;
    const started = performance.now();
    const id = `local-${Date.now().toString(36)}`;
    const imageTargets = state.imageTargets.map(serializableImageTarget).filter(Boolean);
    const imageTarget = serializableImageTarget(imageOptions.imageTarget || null);
    return new Promise(resolve => {
      const timeout = setTimeout(() => {
        state.workerBusy = false;
        log("Background worker took too long; pausing this cycle to keep the browser responsive.");
        resolve({ best: state.lab.best(), elapsed: 0, timeout: true });
      }, 8000);
      state.backgroundWorker.onmessage = event => {
        const payload = event.data || {};
        if (payload.id !== id) return;
        clearTimeout(timeout);
        state.workerBusy = false;
        if (!payload.ok) {
          log(`Background worker failed: ${payload.error}`);
          resolve({ best: state.lab.best(), elapsed: 0 });
          return;
        }
        state.lab.corpus = payload.corpus;
        state.lab.corpora = payload.corpora;
        state.lab.persistentContext = payload.persistentContext || "";
        state.lab.curriculumLevel = payload.curriculumLevel || state.lab.curriculumLevel;
        state.lab.setConfig(payload.config || {});
        const champion = state.lab.importChampion(payload.champion);
        state.lab.generation = payload.generation;
        if (payload.historyPoint) state.lab.history.push(payload.historyPoint);
        if (state.lab.history.length > 160) state.lab.history.shift();
        const elapsed = Math.round(performance.now() - started);
        const maxNeurons = Math.max(...state.lab.population.map(genome => genome.neurons));
        const minNeurons = Math.min(...state.lab.population.map(genome => genome.neurons));
        log(`Generation ${state.lab.generation}: fitness ${champion.fitness.toFixed(4)}, loss ${champion.loss.toFixed(3)}, best ${champion.neurons}n/${champion.synapses}s, population ${minNeurons}-${maxNeurons}n. Background worker.`);
        updateReadout();
        resolve({ best: champion, elapsed });
      };
      state.backgroundWorker.postMessage({
        type: "evolve",
        id,
        corpus: state.lab.corpus,
        corpora: state.lab.corpora,
        persistentContext: state.lab.persistentContext,
        curriculumLevel: state.lab.curriculumLevel,
        config: state.lab.config,
        generation: state.lab.generation,
        champion: state.lab.best().toJSON(),
        imageTargets,
        imageTarget,
        imagePrompt: imageOptions.imagePrompt || el("imagePrompt").value,
        imageLearningRate: Number(el("imageMutation")?.value || 0.012) * 0.5,
        maxChars: Number(state.lab.config.neurons) > 1800 ? 420 : 760
      });
    });
  }

  async function evolveLoop() {
    if (!state.evolving) return;
    setStatus("Evolving");
    await new Promise(resolve => setTimeout(resolve, 20));
    try {
      await evolveStep();
    } catch (error) {
      log(`Evolution stopped: ${error.message}`);
      state.evolving = false;
      el("evolveButton").textContent = "Evolve";
      setStatus("Error");
      return;
    }
    requestAnimationFrame(evolveLoop);
  }

  async function importWikipedia() {
    const title = el("wikiTitle").value.trim();
    if (!title) return;
    setStatus("Fetching Wikipedia");
    try {
      const url = `https://en.wikipedia.org/w/api.php?origin=*&action=query&prop=extracts&explaintext=1&redirects=1&format=json&titles=${encodeURIComponent(title)}`;
      const response = await fetch(url);
      const data = await response.json();
      const pages = data?.query?.pages || {};
      const page = Object.values(pages)[0];
      if (!page?.extract) throw new Error("No article text returned");
      const addition = `\n\n# ${page.title}\n${page.extract}`;
      el("corpusText").value = `${el("corpusText").value}${addition}`.trim();
      state.lab.setCorpus(el("corpusText").value);
      log(`Imported Wikipedia article "${page.title}" (${formatChars(page.extract.length)} chars).`);
      setStatus("Imported");
      updateReadout();
    } catch (error) {
      log(`Wikipedia import failed: ${error.message}`);
      setStatus("Import failed");
    }
  }

  function cleanWikitext(text) {
    return String(text || "")
      .replace(/\{\{[^{}]*\}\}/g, " ")
      .replace(/<ref[^>]*>[\s\S]*?<\/ref>/gi, " ")
      .replace(/<[^>]+>/g, " ")
      .replace(/\[\[File:[^\]]+\]\]/gi, " ")
      .replace(/\[\[Category:[^\]]+\]\]/gi, " ")
      .replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, "$2")
      .replace(/\[\[([^\]]+)\]\]/g, "$1")
      .replace(/={2,}/g, "\n")
      .replace(/\s+\n/g, "\n")
      .replace(/\n{3,}/g, "\n\n")
      .trim();
  }

  async function fetchFullWikipediaArticle(title) {
    const url = `https://en.wikipedia.org/w/api.php?origin=*&action=query&prop=revisions&rvprop=content&rvslots=main&format=json&formatversion=2&redirects=1&titles=${encodeURIComponent(title)}`;
    const response = await fetch(url);
    const data = await response.json();
    const page = data?.query?.pages?.[0];
    const content = page?.revisions?.[0]?.slots?.main?.content;
    if (!content) throw new Error(`No full article returned for ${title}`);
    return { title: page.title || title, text: cleanWikitext(content) };
  }

  async function importWikipediaBatch() {
    const titles = el("wikiBatch").value.split(/\r?\n/).map(title => title.trim()).filter(Boolean);
    if (!titles.length) return;
    setStatus("Loading full articles");
    for (let i = 0; i < titles.length; i++) {
      try {
        const article = await fetchFullWikipediaArticle(titles[i]);
        state.lab.addCorpus(article.title, article.text, Math.min(10, i + 1));
        log(`Loaded full Wikipedia article "${article.title}" as curriculum difficulty ${Math.min(10, i + 1)} (${formatChars(article.text.length)} chars).`);
      } catch (error) {
        log(`Full article load failed for "${titles[i]}": ${error.message}`);
      }
    }
    el("corpusText").value = state.lab.corpus;
    updateReadout();
    setStatus("Curriculum loaded");
  }

  function readFileAsText(file) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => {
        const text = String(reader.result || "");
        resolve(text.length > MAX_IMPORTED_TEXT_CHARS ? text.slice(0, MAX_IMPORTED_TEXT_CHARS) : text);
      };
      reader.onerror = () => reject(reader.error);
      reader.readAsText(file);
    });
  }

  async function readPdfAsText(file) {
    if (location.protocol === "file:") {
      throw new Error("PDF import needs the local server. Open http://localhost:4173 with launch-genesis-lab.bat, then drop the PDF again.");
    }
    if (file.size > 25 * 1024 * 1024) {
      throw new Error("PDF is too large for safe import. Try a smaller PDF or split it first.");
    }
    const response = await fetch(`/api/import/pdf?name=${encodeURIComponent(file.name)}`, {
      method: "POST",
      headers: { "Content-Type": "application/pdf" },
      body: await file.arrayBuffer()
    });
    const payload = await response.json();
    if (!response.ok || !payload.ok) throw new Error(payload.error || "PDF import failed");
    return payload;
  }

  function loadImageTarget(file) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      const image = new Image();
      reader.onload = () => {
        image.onload = () => {
          const size = 48;
          const canvas = document.createElement("canvas");
          canvas.width = size;
          canvas.height = size;
          const ctx = canvas.getContext("2d");
          ctx.drawImage(image, 0, 0, size, size);
          const imageData = ctx.getImageData(0, 0, size, size);
          resolve({ name: file.name, size, pixels: imageData.data, thumbnail: canvas });
        };
        image.onerror = reject;
        image.src = String(reader.result);
      };
      reader.onerror = () => reject(reader.error);
      reader.readAsDataURL(file);
    });
  }

  async function handleFiles(files) {
    setStatus("Importing files");
    for (const file of files) {
      try {
        if (file.type.startsWith("image/")) {
          saveBrowserCheckpoint("before-image-import");
          const target = await loadImageTarget(file);
          state.imageTargets.push(target);
          state.lastImageTarget = target;
          state.lab.best().seeImage(target, 0.22);
          state.lab.lastImageLoss = state.lab.best().trainImage(target, file.name, 0.018);
          log(`Imported image target "${file.name}" and activated visual training (initial loss ${state.lab.lastImageLoss.toFixed(4)}).`);
        } else if (file.type === "application/pdf" || file.name.toLowerCase().endsWith(".pdf")) {
          log(`Extracting text from PDF "${file.name}" safely on the local server...`);
          const pdf = await readPdfAsText(file);
          state.lab.addCorpus(pdf.name || file.name, pdf.text, Number(el("corpusDifficulty")?.value) || 1);
          el("corpusText").value = state.lab.corpus;
          log(`Imported PDF "${file.name}" (${formatChars(pdf.chars || pdf.text.length)} chars${pdf.truncated ? ", capped for safety" : ""}).`);
        } else {
          const text = await readFileAsText(file);
          state.lab.addCorpus(file.name, text, Number(el("corpusDifficulty")?.value) || 1);
          el("corpusText").value = state.lab.corpus;
          log(`Imported text file "${file.name}" (${formatChars(text.length)} chars${file.size > text.length ? ", capped for safety" : ""}).`);
        }
      } catch (error) {
        log(`Could not import "${file.name}": ${error.message}`);
      }
      await new Promise(resolve => setTimeout(resolve, 0));
    }
    state.lab.rebuildCurriculumCorpus();
    el("corpusText").value = state.lab.corpus;
    renderTargets();
    updateReadout();
    setStatus("Import complete");
  }

  function renderTargets() {
    const strip = el("targetStrip");
    strip.innerHTML = "";
    for (const target of state.imageTargets.slice(-5).reverse()) {
      const card = document.createElement("div");
      card.className = "target-card";
      const canvas = document.createElement("canvas");
      canvas.width = target.size;
      canvas.height = target.size;
      canvas.getContext("2d").putImageData(new ImageData(new Uint8ClampedArray(target.pixels), target.size, target.size), 0, 0);
      const label = document.createElement("span");
      label.textContent = target.name;
      card.append(canvas, label);
      strip.append(card);
    }
  }

  function restoreImageTargets(targets) {
    if (!Array.isArray(targets)) return;
    state.imageTargets = targets
      .map(target => {
        const size = Number(target.size) || 48;
        const rawPixels = target.pixels?.value || target.pixels || [];
        const pixels = Array.isArray(rawPixels)
          ? rawPixels
          : ArrayBuffer.isView(rawPixels)
            ? Array.from(rawPixels)
            : Object.keys(rawPixels).sort((a, b) => Number(a) - Number(b)).map(key => rawPixels[key]);
        if (pixels.length < size * size * 4) return null;
        return {
          name: target.name || "image target",
          size,
          pixels: new Uint8ClampedArray(pixels.slice(0, size * size * 4).map(value => clamp(Number(value) || 0, 0, 255)))
        };
      })
      .filter(Boolean);
    state.lastImageTarget = state.imageTargets.at(-1) || null;
    renderTargets();
  }

  function paintGeneratedImage(rendered) {
    const canvas = el("imageCanvas");
    canvas.width = rendered.size;
    canvas.height = rendered.size;
    const ctx = canvas.getContext("2d");
    ctx.putImageData(new ImageData(rendered.pixels, rendered.size, rendered.size), 0, 0);
  }

  async function generateChat() {
    syncConfigToLab();
    const prompt = el("chatPrompt").value.trim() || "Hello";
    const length = Number(el("chatLength").value);
    const temperature = Number(el("temperature").value);
    const localPrimer = `${CHAT_PRIMER_TEXT}\n${CONTROL_HUMAN} ${prompt} ${CONTROL_ASSISTANT}`;
    const user = document.createElement("div");
    user.className = "message user";
    user.textContent = prompt;
    const model = document.createElement("div");
    model.className = "message model";
    model.textContent = state.serverChatAvailable ? "Thinking through server organism..." : "Thinking locally...";
    el("chatHistory").append(user, model);
    el("chatHistory").scrollTop = el("chatHistory").scrollHeight;
    await new Promise(resolve => setTimeout(resolve, 30));
    if (state.serverChatAvailable) {
      try {
        // Server chat lets the organism's own generated command tokens trigger
        // allowlisted tools. The frontend only displays the process.
        setToolStatus("Thinking...");
        const response = await fetch("/api/chat", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ prompt, length, temperature, maxToolRounds: 2 })
        });
        const payload = await response.json();
        if (!payload.ok) throw new Error(payload.error || "Server chat failed");
        model.textContent = safeChatText(payload.text || payload.raw || "", chatFallbackFor(prompt));
        if (payload.tools?.length) {
          const toolNote = document.createElement("div");
          toolNote.className = "message model";
          toolNote.textContent = payload.tools.map(tool => `Used ${tool.kind}: ${tool.value}\n${tool.source}`).join("\n\n");
          el("chatHistory").append(toolNote);
          setToolStatus(`Tool sense used ${payload.tools.length} request(s).`);
        } else {
          setToolStatus("No tool request emitted.");
        }
      } catch (error) {
        setToolStatus(`Server tool chat unavailable, falling back locally. ${error.message}`);
        state.lab.best().adaptDialogue(localPrimer, 0.02, 850);
        const generated = safeChatText(state.lab.best().generate(prompt, length, temperature), chatFallbackFor(prompt));
        model.textContent = generated;
        state.lab.remember(`User: ${prompt}\nGenesis: ${generated}`);
      }
    } else {
      state.lab.best().adaptDialogue(localPrimer, 0.02, 850);
      const generated = safeChatText(state.lab.best().generate(prompt, length, temperature), chatFallbackFor(prompt));
      model.textContent = generated;
      state.lab.remember(`User: ${prompt}\nGenesis: ${generated}`);
      setToolStatus("Local-only mode. Launch the server to enable controlled internet sense.");
    }
    el("chatHistory").scrollTop = el("chatHistory").scrollHeight;
    updateReadout();
  }

  function rememberConversation() {
    const text = Array.from(document.querySelectorAll(".message")).map(node => node.textContent).join("\n");
    state.lab.remember(text);
    log("Stored chat context in persistent organism memory.");
    updateReadout();
  }

  function startSpeechInput() {
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!SpeechRecognition) {
      log("Speech recognition is not available in this browser.");
      return;
    }
    const recognizer = new SpeechRecognition();
    recognizer.lang = "en-US";
    recognizer.interimResults = false;
    recognizer.maxAlternatives = 1;
    el("speechButton").textContent = "Listening";
    recognizer.onresult = event => {
      const text = event.results?.[0]?.[0]?.transcript || "";
      if (text) {
        el("chatPrompt").value = text;
        state.lab.remember(`Speech input: ${text}`);
        log(`Speech captured into chat prompt: "${text}"`);
      }
    };
    recognizer.onerror = event => log(`Speech recognition stopped: ${event.error || "unknown error"}`);
    recognizer.onend = () => {
      el("speechButton").textContent = "Speak";
    };
    recognizer.start();
  }

  function renderImage() {
    const size = Number(el("imageSize").value);
    const prompt = el("imagePrompt").value;
    setStatus("Rendering image");
    const rendered = state.lab.best().renderImage(prompt, size);
    paintGeneratedImage(rendered);
    setStatus("Rendered");
  }

  async function evolveImage() {
    const target = state.lastImageTarget || state.imageTargets.at(-1);
    if (!target) {
      log("Import an image target first, then run image evolution.");
      return;
    }
    const originalMutation = state.lab.config.mutation;
    state.lab.config.mutation = Number(el("imageMutation").value);
    saveBrowserCheckpoint("before-image-evolution");
    setStatus("Evolving image");
    const button = el("evolveImageButton");
    button.disabled = true;
    try {
      for (let i = 0; i < 6; i++) {
        setStatus(`Evolving image ${i + 1}/6`);
        const result = await evolveStep({ imageTarget: target, imagePrompt: el("imagePrompt").value });
        if (result?.timeout) break;
        if (i === 2) saveBrowserCheckpoint("mid-image-evolution");
        await new Promise(resolve => setTimeout(resolve, 80));
      }
    } catch (error) {
      log(`Image evolution paused safely: ${error.message}`);
      setStatus("Image paused");
    } finally {
      state.lab.config.mutation = originalMutation;
      button.disabled = false;
      saveBrowserCheckpoint("after-image-evolution");
    }
    renderImage();
    setStatus("Image evolved");
  }

  function seeImageTarget() {
    const target = state.lastImageTarget || state.imageTargets.at(-1);
    if (!target) {
      log("Import an image target first, then the organism can see it.");
      return;
    }
    state.lab.best().seeImage(target, 0.35);
    state.lab.lastImageLoss = state.lab.best().trainImage(target, el("imagePrompt").value, 0.025);
    log(`Encoded and trained visual target "${target.name}" into the champion (loss ${state.lab.lastImageLoss.toFixed(4)}).`);
    renderImage();
    updateReadout();
  }

  function addCurrentCorpus() {
    const text = el("corpusText").value;
    const name = el("corpusName").value || `corpus-${state.lab.corpora.length + 1}`;
    const difficulty = Number(el("corpusDifficulty").value) || 1;
    state.lab.addCorpus(name, text, difficulty);
    el("corpusText").value = state.lab.corpus;
    log(`Added "${name}" to curriculum at difficulty ${difficulty}.`);
    updateReadout();
  }

  function exportModel() {
    const data = {
      format: "genesis-lab-genome-v1",
      exportedAt: new Date().toISOString(),
      corpus: state.lab.corpus,
      corpora: state.lab.corpora,
      persistentContext: state.lab.persistentContext,
      memoryBank: state.lab.memoryBank,
      curriculumLevel: state.lab.curriculumLevel,
      imageTargets: state.imageTargets.map(target => ({
        name: target.name,
        size: target.size,
        pixels: Array.from(target.pixels)
      })),
      config: state.lab.config,
      generation: state.lab.generation,
      champion: state.lab.best().toJSON()
    };
    const blob = new Blob([JSON.stringify(data)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `genesis-lab-generation-${state.lab.generation}.json`;
    anchor.style.display = "none";
    document.body.appendChild(anchor);
    anchor.click();
    setTimeout(() => {
      URL.revokeObjectURL(url);
      anchor.remove();
    }, 1000);
    log(`Exported model generation ${state.lab.generation}.`);
  }

  async function importModel(file) {
    const text = await readFileAsText(file);
    const data = JSON.parse(text);
    const champion = data.champion || data.genome || (data.neurons && data.synapses ? data : null);
    if (!champion) throw new Error("No champion genome found");
    el("corpusText").value = data.corpus || el("corpusText").value;
    state.lab.setCorpus(el("corpusText").value);
    if (Array.isArray(data.corpora)) state.lab.corpora = data.corpora;
    if (typeof data.persistentContext === "string") state.lab.persistentContext = data.persistentContext;
    if (Array.isArray(data.memoryBank)) state.lab.memoryBank = data.memoryBank.slice(-180);
    if (data.curriculumLevel) state.lab.curriculumLevel = data.curriculumLevel;
    state.lab.setConfig(data.config || {});
    const genome = state.lab.importChampion(champion, { lazyPopulation: true });
    restoreImageTargets(data.imageTargets);
    el("modelInput").value = "";
    log(`Imported model: generation ${genome.generation}, ${genome.neurons} neurons, ${genome.synapses} synapses. Population will refill gradually during evolution.`);
    updateReadout();
    renderImage();
  }

  async function refreshNetworkStatus() {
    try {
      const response = await fetch("/api/status");
      const status = await response.json();
      state.serverChatAvailable = true;
      if (el("chatModeStatus")) el("chatModeStatus").textContent = "Server organism can use controlled Wikipedia tool tokens";
      el("workerStat").textContent = status.workers ? String(status.workers) : "local";
      const base = status.addresses?.[0] || location.origin;
      el("workerUrl").value = `${base}/worker.html`;
      updateServerEvolutionStatus(status.serverEvolution);
    } catch {
      state.serverChatAvailable = false;
      if (el("chatModeStatus")) el("chatModeStatus").textContent = "Local-only browser generation";
      el("workerStat").textContent = "local";
      el("workerUrl").value = `${location.origin}/worker.html`;
      updateServerEvolutionStatus(null);
    }
  }

  function connectToolSocket() {
    if (location.protocol === "file:") {
      setToolStatus("Local file mode. Start the Node server for controlled internet tool use.");
      return;
    }
    try {
      if (state.ws) state.ws.close();
      const protocol = location.protocol === "https:" ? "wss:" : "ws:";
      state.ws = new WebSocket(`${protocol}//${location.host}/ws`);
      state.ws.addEventListener("message", event => {
        const payload = JSON.parse(event.data);
        if (payload.type === "thinking") {
          if (payload.phase === "searching") {
            const labels = (payload.commands || []).map(command => `${command.kind}:${command.value}`).join(", ");
            setToolStatus(`Searching: ${labels}`);
          } else if (payload.phase === "generating") {
            setToolStatus("Thinking...");
          } else if (payload.phase === "done") {
            setToolStatus(payload.toolSteps ? `Tool sense complete: ${payload.toolSteps} result(s).` : "Thinking complete.");
          }
        }
      if (payload.type === "tool") {
          setToolStatus(payload.ok ? `Tool result: ${payload.command} ${payload.value}` : `Tool blocked: ${payload.error}`);
        }
        if (payload.type === "evolution" && payload.immigrants) {
          log(`Server diversity refresh: ${payload.immigrants} fresh 400-neuron immigrant genomes added.`);
        }
        if (payload.type === "evolution" && payload.selfGenerated) {
          log(`Server self-training accepted ${payload.selfGenerated} generated dialogue pair(s).`);
        }
      });
      state.ws.addEventListener("open", () => setToolStatus("Controlled internet sense connected."));
      state.ws.addEventListener("close", () => setToolStatus("Tool socket closed. Local/server HTTP still works."));
    } catch (error) {
      setToolStatus(`Tool socket unavailable: ${error.message}`);
    }
  }

  function updateServerEvolutionStatus(snapshot) {
    if (!el("serverStateMetric")) return;
    if (!snapshot) {
      el("serverStateMetric").textContent = "offline";
      el("serverGenMetric").textContent = "--";
      el("serverSaveMetric").textContent = "--";
      return;
    }
    el("serverStateMetric").textContent = snapshot.running ? "running" : "paused";
    el("serverGenMetric").textContent = `Gen ${snapshot.generation || 0}`;
    el("serverSaveMetric").textContent = snapshot.savePath ? "disk" : "--";
  }

  function serverPayload() {
    syncConfigToLab();
    return {
      corpus: state.lab.corpus,
      corpora: state.lab.corpora,
      persistentContext: state.lab.persistentContext,
      curriculumLevel: state.lab.curriculumLevel,
      imageTargets: state.imageTargets.map(target => ({
        name: target.name,
        size: target.size,
        pixels: Array.from(target.pixels)
      })),
      config: state.lab.config,
      champion: state.lab.best().toJSON(),
      delayMs: 180
    };
  }

  async function startServerEvolution() {
    const response = await fetch("/api/server/start", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ delayMs: 180 })
    });
    const payload = await response.json();
    updateServerEvolutionStatus(payload.serverEvolution);
    log("Server autopilot started using the champion already saved on the server. Use Sync when you intentionally want to replace it with the browser model.");
    setStatus("Server evolving");
  }

  async function stopServerEvolution() {
    const response = await fetch("/api/server/stop", { method: "POST" });
    const payload = await response.json();
    updateServerEvolutionStatus(payload.serverEvolution);
    log("Server autopilot stopped and saved.");
    setStatus("Server paused");
  }

  async function syncToServer() {
    const response = await fetch("/api/server/sync", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(serverPayload())
    });
    const payload = await response.json();
    updateServerEvolutionStatus(payload.serverEvolution);
    log(payload.blockedDowngrade
      ? "Server blocked this sync because it would downgrade the saved large champion. Pull the server champion first, or intentionally allow a downgrade in code."
      : "Sent the current browser model to the server and saved it.");
    setStatus("Server synced");
  }

  async function pullFromServer() {
    const wasEvolving = state.evolving;
    state.evolving = false;
    el("evolveButton").textContent = "Evolve";
    el("pauseButton").textContent = "Paused";
    setStatus("Pulling champion");
    log("Pulling compact server champion. Evolution is paused while the genome is installed.");
    const response = await fetch("/api/server/champion?corpus=0");
    const payload = await response.json();
    if (!payload.model?.champion) throw new Error("No server champion returned");
    await new Promise(resolve => setTimeout(resolve, 0));
    if (payload.model.corpus) {
      state.lab.corpus = payload.model.corpus;
      el("corpusText").value = payload.model.corpus;
    }
    if (Array.isArray(payload.model.corpora)) state.lab.corpora = payload.model.corpora;
    if (typeof payload.model.persistentContext === "string") state.lab.persistentContext = payload.model.persistentContext;
    if (Array.isArray(payload.model.memoryBank)) state.lab.memoryBank = payload.model.memoryBank.slice(-180);
    if (payload.model.curriculumLevel) state.lab.curriculumLevel = payload.model.curriculumLevel;
    state.lab.setConfig(payload.model.config || {});
    const genome = state.lab.importChampion(payload.model.champion, { lazyPopulation: true });
    restoreImageTargets(payload.model.imageTargets);
    updateServerEvolutionStatus(payload.serverEvolution);
    log(`Pulled server champion: generation ${genome.generation}, ${genome.neurons} neurons, ${genome.synapses} synapses. Population will refill gradually during evolution.`);
    updateReadout();
    requestAnimationFrame(renderImage);
    setStatus("Champion pulled");
    if (wasEvolving) log("Evolution was paused for the pull. Press Evolve when you are ready to continue.");
  }

  async function publishJob() {
    syncConfigToLab();
    const job = {
      id: `job-${Date.now().toString(36)}`,
      genome: state.lab.best().toJSON(),
      corpus: state.lab.corpus.slice(0, 6000),
      rounds: 4,
      priority: 5,
      mutation: state.lab.config.mutation,
      scalarMutation: state.lab.config.scalarMutation,
      neurons: state.lab.config.neurons,
      synapses: state.lab.config.synapses,
      vocabSize: state.lab.config.vocabSize,
      maxChars: 620
    };
    await fetch("/api/job", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(job)
    });
    log(`Published LAN job ${job.id}.`);
    setStatus("Job published");
  }

  async function collectResults() {
    const response = await fetch("/api/results");
    const payload = await response.json();
    const results = payload.results || [];
    if (!results.length) {
      log("No LAN worker results are waiting.");
      return;
    }
    let accepted = 0;
    for (const result of results) {
      const genome = NeuralGenome.fromJSON(result.genome);
      genome.setVocab(state.lab.vocab);
      genome.evaluateText(state.lab.corpus, 760);
      if (genome.fitness > state.lab.best().fitness) {
        state.lab.population[0] = genome;
        state.lab.population.sort((a, b) => b.fitness - a.fitness);
        accepted += 1;
      }
    }
    log(`Collected ${results.length} worker result(s), accepted ${accepted}.`);
    updateReadout();
  }

  function bindEvents() {
    document.querySelectorAll(".mode-button").forEach(button => {
      button.addEventListener("click", () => switchView(button.dataset.view));
    });

    ["neuronInput", "synapseInput", "populationInput", "mutationInput"].forEach(id => {
      el(id).addEventListener("input", () => {
        syncConfigToLab();
        updateReadout();
      });
    });

    el("seedButton").addEventListener("click", () => {
      syncConfigToLab();
      state.lab.seed();
      log(`Seeded population at ${state.lab.config.neurons} neurons and ${state.lab.config.synapses} synapses.`);
      updateReadout();
      renderImage();
    });

    el("evolveButton").addEventListener("click", () => {
      state.evolving = !state.evolving;
      el("evolveButton").textContent = state.evolving ? "Stop" : "Evolve";
      el("pauseButton").textContent = state.evolving ? "Pause" : "Paused";
      if (state.evolving) evolveLoop();
      else setStatus("Paused");
    });

    el("pauseButton").addEventListener("click", () => {
      state.evolving = false;
      el("evolveButton").textContent = "Evolve";
      el("pauseButton").textContent = "Paused";
      setStatus("Paused");
    });

    el("wikiButton").addEventListener("click", importWikipedia);
    el("wikiBatchButton").addEventListener("click", importWikipediaBatch);
    el("addCorpusButton").addEventListener("click", addCurrentCorpus);
    el("fileInput").addEventListener("change", event => handleFiles(event.target.files));

    const drop = document.querySelector(".drop-zone");
    drop.addEventListener("dragover", event => {
      event.preventDefault();
      drop.style.borderColor = "rgba(84, 210, 196, 0.85)";
    });
    drop.addEventListener("dragleave", () => {
      drop.style.borderColor = "";
    });
    drop.addEventListener("drop", event => {
      event.preventDefault();
      drop.style.borderColor = "";
      handleFiles(event.dataTransfer.files);
    });

    el("chatButton").addEventListener("click", generateChat);
    el("speechButton").addEventListener("click", startSpeechInput);
    el("rememberChatButton").addEventListener("click", rememberConversation);
    el("renderImageButton").addEventListener("click", renderImage);
    el("seeImageButton").addEventListener("click", seeImageTarget);
    el("evolveImageButton").addEventListener("click", evolveImage);
    el("topologyButton").addEventListener("click", toggleTopologyView);
    el("resetFitnessButton").addEventListener("click", resetFitnessGraph);
    el("exportButton").addEventListener("click", exportModel);
    el("importButton").addEventListener("click", () => el("modelInput").click());
    el("modelInput").addEventListener("change", event => {
      if (event.target.files[0]) importModel(event.target.files[0]).catch(error => log(`Import failed: ${error.message}`));
    });
    el("publishJobButton").addEventListener("click", publishJob);
    el("collectResultsButton").addEventListener("click", collectResults);
    el("serverStartButton").addEventListener("click", () => startServerEvolution().catch(error => log(`Server start failed: ${error.message}`)));
    el("serverStopButton").addEventListener("click", () => stopServerEvolution().catch(error => log(`Server stop failed: ${error.message}`)));
    el("serverSyncButton").addEventListener("click", () => syncToServer().catch(error => log(`Server sync failed: ${error.message}`)));
    el("serverPullButton").addEventListener("click", () => pullFromServer().catch(error => log(`Server pull failed: ${error.message}`)));
    el("copyWorkerUrl").addEventListener("click", async () => {
      await navigator.clipboard.writeText(el("workerUrl").value);
      setStatus("Worker URL copied");
    });
  }

  function cleanupRuntime() {
    state.evolving = false;
    cancelAnimationFrame(state.topologyRaf);
    state.topologyRaf = 0;
    if (state.statusTimer) clearInterval(state.statusTimer);
    if (state.ws) {
      state.ws.close();
      state.ws = null;
    }
    if (state.backgroundWorker) {
      state.backgroundWorker.terminate();
      state.backgroundWorker = null;
    }
  }

  function boot() {
    el("corpusText").value = DEFAULT_SEED_TEXT;
    state.lab.setCorpus(DEFAULT_SEED_TEXT);
    bindEvents();
    try {
      if (location.protocol === "file:") {
        log("Opened as a local file, so browser Web Workers are blocked. Using main-thread evolution. Launch the local server for background workers.");
      } else {
        state.backgroundWorker = new Worker("local-evolve-worker.js");
        log("Background Web Worker ready for browser-side evolution cycles.");
      }
    } catch (error) {
      log(`Background Web Worker unavailable. Using main-thread evolution. ${error.message}`);
    }
    log("Ready. This app uses no external AI model or AI API.");
    log(`400 neurons is the default seed size; the current UI allows up to ${MAX_NEURONS.toLocaleString()} neurons and ${MAX_SYNAPSES.toLocaleString()} synapses.`);
    updateReadout();
    renderImage();
    if (location.hash === "#topology") toggleTopologyView();
    connectToolSocket();
    refreshNetworkStatus();
    state.statusTimer = setInterval(refreshNetworkStatus, 5000);
    window.addEventListener("beforeunload", cleanupRuntime, { once: true });
  }

  boot();
})();
