(function () {
  const { EvolutionLab, NeuralGenome, DEFAULT_SEED_TEXT, CHAT_PRIMER_TEXT, CONTROL_HUMAN, CONTROL_ASSISTANT, CONTROL_TURN_END, MAX_NEURONS, MAX_SYNAPSES, DEFAULT_VOCAB_SIZE, clamp, cleanGeneratedText, chatQualityScore, isUsefulTrainingText, sanitizePersistentContext, sanitizeMemoryBank, trainingValueScore } = window.GenesisEngine;

  const el = id => document.getElementById(id);
  const state = {
    lab: new EvolutionLab(),
    evolving: false,
    imageTargets: [],
    lastImageTarget: null,
    lastCycleAt: 0,
    backgroundWorker: null,
    workerBusy: false,
    workerTimeoutMs: 14000,
    workerTimeouts: 0,
    workerCooldownUntil: 0,
    ws: null,
    serverChatAvailable: false,
    topologyActive: false,
    topologyRaf: 0,
    topologyLastDraw: 0,
    lastActivityAt: 0,
    cachedActivity: null,
    dreaming: false,
    deepDreaming: false,
    reflecting: false,
    lastChatPair: null,
    typingLearnTimer: 0,
    lastTypingLearnAt: 0,
    lastTypingLearnText: "",
    lastMemoryPressureLog: 0,
    statusTimer: 0
  };
  const MAX_IMPORTED_TEXT_CHARS = 1_200_000;

  function safeChatText(text, fallback = "I am still stabilizing my chat vocabulary. Try a little more text training, then ask again.") {
    const cleaned = cleanGeneratedText(String(text || ""), 2400);
    return cleaned && chatQualityScore(cleaned) >= 0.55 ? cleaned : fallback;
  }

  function chatFallbackFor(prompt) {
    return /^(hi|hey|hello|yo|sup)[\s!.?]*$/i.test(prompt || "")
      ? "Hey. I am awake. My chat vocabulary is cleaned up now, and I am still learning from the local organism."
      : "I am still stabilizing my chat vocabulary. Try a little more text training, then ask again.";
  }

  const views = {
    train: {
      title: "Training Console",
      subtitle: "Import real text and images, then evolve a local sparse neural organism."
    },
    chat: {
      title: "Chat Mode",
      subtitle: "A subword-token sparse organism generated by this app, not an external AI service."
    },
    image: {
      title: "Image Mode",
      subtitle: "A local neural pattern generator that can evolve toward imported visual targets."
    },
    network: {
      title: "Network Compute",
      subtitle: "Use browser tabs and LAN devices you control to search for stronger genomes."
    }
  };

  function log(message) {
    const line = `[${new Date().toLocaleTimeString()}] ${message}`;
    el("trainingLog").textContent = `${line}\n${el("trainingLog").textContent}`.slice(0, 8000);
  }

  function setStatus(message) {
    el("statusPill").textContent = message;
  }

  function setToolStatus(message) {
    if (el("toolStatus")) el("toolStatus").textContent = message;
  }

  function invalidateActivityCache() {
    state.cachedActivity = null;
    state.lastActivityAt = 0;
  }

  function syncTrainingControls() {
    if (el("evolveButton")) el("evolveButton").textContent = state.evolving ? "Stop" : "Evolve";
    if (el("pauseButton")) el("pauseButton").textContent = state.evolving ? "Pause" : "Paused";
    if (el("dreamButton")) {
      el("dreamButton").disabled = state.evolving || state.dreaming || state.deepDreaming || state.reflecting;
      el("dreamButton").textContent = state.dreaming ? "Dreaming" : "Dream";
    }
    if (el("spiralButton")) {
      const spiral = state.lab?.spiralStatus ? state.lab.spiralStatus() : { active: false };
      el("spiralButton").disabled = state.dreaming || state.deepDreaming || state.reflecting;
      el("spiralButton").textContent = spiral.active ? `Stop Mirror (${spiral.remaining})` : "Trigger Mirror";
    }
    if (el("deepDreamButton")) {
      el("deepDreamButton").disabled = state.evolving || state.dreaming || state.deepDreaming || state.reflecting;
      el("deepDreamButton").textContent = state.deepDreaming ? "DEEP Dreaming" : "DEEP Dream";
    }
    if (el("deepDreamLastButton")) el("deepDreamLastButton").disabled = state.evolving || state.dreaming || state.deepDreaming || state.reflecting;
  }

  function readyToTrain() {
    setStatus("Ready to train");
    log("ready to train");
    syncTrainingControls();
  }

  function sanitizeCorpora(corpora = []) {
    let quarantined = 0;
    const cleaned = [];
    for (const corpus of corpora || []) {
      const isSelfGenerated = /\b(self-generated|self-tune|deep-reflection|mirror|dream|tool|context-tool)\b/i.test(corpus?.name || "");
      const assistantText = isSelfGenerated && String(corpus?.text || "").includes(CONTROL_ASSISTANT)
        ? String(corpus.text).split(CONTROL_ASSISTANT).slice(1).join(" ").split(CONTROL_TURN_END)[0]
        : corpus?.text || "";
      if (isSelfGenerated && (!isUsefulTrainingText(assistantText, { minQuality: 0.56, minEntropy: 0.46, minDialogue: 0.42, minLength: 48, maxOneLetterRatio: 0.16, maxContamination: 0.3, maxRepetition: 0.38 }) || (trainingValueScore && trainingValueScore(assistantText) < 0.45))) {
        quarantined += 1;
        continue;
      }
      if (corpus?.text) cleaned.push(corpus);
    }
    return { corpora: cleaned, quarantined };
  }

  function serializableImageTarget(target) {
    if (!target) return null;
    return {
      name: target.name || "image target",
      size: target.size || 48,
      pixels: Array.from(target.pixels || [])
    };
  }

  function saveBrowserCheckpoint(reason = "checkpoint") {
    try {
      const checkpoint = {
        format: "genesis-lab-browser-checkpoint-v1",
        reason,
        savedAt: new Date().toISOString(),
        corpus: state.lab.corpus,
        corpora: state.lab.corpora,
        persistentContext: state.lab.persistentContext,
        userProfile: state.lab.userProfile,
        memorySummary: state.lab.memorySummary,
        recentTranscript: state.lab.recentTranscript,
        memoryBank: state.lab.memoryBank,
        mirrorCorpus: state.lab.mirrorCorpus,
        spiralPhase: state.lab.spiralPhase,
        curriculumLevel: state.lab.curriculumLevel,
        imageTargets: state.imageTargets.map(serializableImageTarget).filter(Boolean),
        config: state.lab.config,
        generation: state.lab.generation,
        champion: state.lab.best().toJSON()
      };
      localStorage.setItem("genesis-lab-last-safe-checkpoint", JSON.stringify(checkpoint));
      return true;
    } catch (error) {
      log(`Checkpoint skipped: ${error.message}`);
      return false;
    }
  }

  function readConfig() {
    return {
      neurons: clamp(Number(el("neuronInput").value) || 400, 64, MAX_NEURONS),
      synapses: clamp(Number(el("synapseInput").value) || 1400, 128, MAX_SYNAPSES),
      populationSize: clamp(Number(el("populationInput").value) || 10, 4, 24),
      mutation: clamp(Number(el("mutationInput").value) || 0.035, 0.001, 0.2),
      scalarMutation: state.lab?.config?.scalarMutation ?? 0.028,
      vocabSize: state.lab?.config?.vocabSize ?? DEFAULT_VOCAB_SIZE,
      gradientSteps: state.lab?.config?.gradientSteps ?? 2,
      gradientLearningRate: state.lab?.config?.gradientLearningRate ?? 0.016
    };
  }

  function syncConfigToLab() {
    state.lab.setConfig(readConfig());
    if (state.lab.corpora.length <= 1) state.lab.setCorpus(el("corpusText").value);
  }

  function formatChars(count) {
    if (count > 1_000_000) return `${(count / 1_000_000).toFixed(1)}m`;
    if (count > 1_000) return `${(count / 1_000).toFixed(1)}k`;
    return String(count);
  }

  function updateReadout() {
    const best = state.lab.best();
    const now = performance.now();
    const activityPrompt = el("chatPrompt")?.value || el("corpusText")?.value || "";
    if (!state.cachedActivity || now - state.lastActivityAt > (state.evolving ? 900 : 350)) {
      state.cachedActivity = best?.getActivity(activityPrompt);
      state.lastActivityAt = now;
    }
    const activity = state.cachedActivity;
    const spiral = state.lab.spiralStatus ? state.lab.spiralStatus() : { active: false, remaining: 0 };
    const neuronCounts = state.lab.population.map(genome => genome.neurons);
    const synapseCounts = state.lab.population.map(genome => genome.synapses);
    const topology = {
      bestNeurons: best?.neurons || 0,
      minNeurons: neuronCounts.length ? Math.min(...neuronCounts) : 0,
      maxNeurons: neuronCounts.length ? Math.max(...neuronCounts) : 0,
      avgNeurons: neuronCounts.length ? Math.round(neuronCounts.reduce((sum, value) => sum + value, 0) / neuronCounts.length) : 0,
      bestSynapses: best?.synapses || 0,
      minSynapses: synapseCounts.length ? Math.min(...synapseCounts) : 0,
      maxSynapses: synapseCounts.length ? Math.max(...synapseCounts) : 0,
      avgSynapses: synapseCounts.length ? Math.round(synapseCounts.reduce((sum, value) => sum + value, 0) / synapseCounts.length) : 0
    };
    const speciesCount = Math.max(1, state.lab.species.length || (best ? 1 : 0));
    const bestSpecies = best?.speciesId && best.speciesId !== "unassigned" ? best.speciesId : "s1";
    el("generationLabel").textContent = `Gen ${state.lab.generation}`;
    el("fitnessStat").textContent = (best?.fitness || 0).toFixed(3);
    el("corpusStat").textContent = `${formatChars(state.lab.corpus.length)} chars`;
    el("vocabStat").textContent = String(state.lab.vocab.length);
    el("lossMetric").textContent = Number.isFinite(best?.loss) && best.loss < 900 ? best.loss.toFixed(3) : "--";
    el("fitnessStat").textContent = (best?.fitness || 0).toFixed(3);
    el("speciesMetric").textContent = best ? `${topology.bestNeurons}n best / ${topology.maxNeurons}n max / ${bestSpecies} of ${speciesCount}` : "--";
    el("cycleMetric").textContent = state.lab.history.length ? `${state.lab.history.at(-1).elapsed}ms` : "--";
    el("neuronInput").value = state.lab.config.neurons;
    el("synapseInput").value = state.lab.config.synapses;
    el("populationInput").value = state.lab.config.populationSize;
    el("modelReadout").textContent = JSON.stringify({
      generation: state.lab.generation,
      neurons: best?.neurons,
      synapses: best?.synapses,
      population: state.lab.population.length,
      speciesCount,
      bestSpecies,
      topology,
      vocab: state.lab.vocab.length,
      fitness: best?.fitness,
      loss: best?.loss,
      naturalness: best?.trainingValueScore || 0,
      linguisticScore: best?.linguisticScore || 0,
      speechCoherence: best?.speechCoherenceScore || 0,
      passiveLearning: best?.passiveLearningScore || 0,
      contamination: best?.contaminationScore || 0,
      repetition: best?.repetitionScore || 0,
      humanFeedback: best?.humanFeedbackScore || 0,
      sensoryGateEfficiency: best?.sensoryGateEfficiency || 0,
      toolConfidence: best?.toolConfidence || 0,
      userProfileStrength: best?.userProfileStrength || 0,
      wakeCycles: best?.wakeCycles || 0,
      toolUseCount: best?.toolUseCount || 0,
      corpusChars: state.lab.corpus.length,
      imageTargets: state.imageTargets.length,
      visualTrainingActive: state.imageTargets.length > 0,
      corpora: state.lab.corpora.length,
      curriculumLevel: state.lab.curriculumLevel,
      spiralMode: spiral,
      mirrorCorpus: state.lab.mirrorCorpus?.length || 0,
      userProfileChars: state.lab.userProfile?.length || 0,
      species: state.lab.species.length,
      personality: Array.from(best?.personality || []).slice(0, 6).map(value => Number(value.toFixed(3))),
      maxNeuronLimit: MAX_NEURONS,
      maxSynapseLimit: MAX_SYNAPSES,
      externalAI: false
    }, null, 2);
    if (el("personalityReadout")) {
      el("personalityReadout").textContent = `personality ${Array.from(best?.personality || []).slice(0, 8).map(value => value.toFixed(2)).join(" ")}`;
    }
    if (el("imageReadout")) {
      el("imageReadout").textContent = JSON.stringify({
        visualMemory: Array.from(best?.visualMemory || []).slice(0, 8).map(value => Number(value.toFixed(3))),
        targets: state.imageTargets.length,
        lastImageLoss: state.lab.lastImageLoss == null ? null : Number(state.lab.lastImageLoss.toFixed(5)),
        activeTarget: state.lastImageTarget?.name || null,
        autoencoder: "visual-latent trainImage active"
      }, null, 2);
    }
    drawFitness();
    drawActivity(activity);
    syncTrainingControls();
  }

  function drawFitness() {
    const canvas = el("fitnessCanvas");
    const ctx = canvas.getContext("2d");
    const width = canvas.width;
    const height = canvas.height;
    ctx.clearRect(0, 0, width, height);
    ctx.fillStyle = "#050805";
    ctx.fillRect(0, 0, width, height);
    ctx.strokeStyle = "rgba(244, 240, 223, 0.08)";
    ctx.lineWidth = 1;
    for (let i = 1; i < 5; i++) {
      const y = (height / 5) * i;
      ctx.beginPath();
      ctx.moveTo(0, y);
      ctx.lineTo(width, y);
      ctx.stroke();
    }

    const points = state.lab.history;
    if (points.length < 2) return;
    const max = Math.max(...points.map(point => point.fitness), 0.001);
    ctx.strokeStyle = "#b9f26d";
    ctx.lineWidth = 3;
    ctx.beginPath();
    points.forEach((point, index) => {
      const x = (index / (points.length - 1)) * width;
      const y = height - (point.fitness / max) * (height - 20) - 10;
      if (index === 0) ctx.moveTo(x, y);
      else ctx.lineTo(x, y);
    });
    ctx.stroke();
  }

  function resetFitnessGraph() {
    state.lab.history = [];
    drawFitness();
    updateReadout();
    log("Fitness graph reset. Champion, population, training data, and server model were left unchanged.");
  }

  function drawActivity(activity) {
    const canvas = el("activityCanvas");
    if (!canvas || !activity) return;
    const ctx = canvas.getContext("2d");
    const width = canvas.width;
    const height = canvas.height;
    ctx.clearRect(0, 0, width, height);
    ctx.fillStyle = "#050805";
    ctx.fillRect(0, 0, width, height);
    const buckets = activity.buckets || [];
    const cell = width / Math.max(1, buckets.length);
    const noisePressure = Number(activity.noisePressure || 0);
    const activityScale = 0.38 + Math.min(1, noisePressure) * 0.62;
    for (let i = 0; i < buckets.length; i++) {
      const value = buckets[i] * activityScale;
      const hue = 88 + value * 90;
      ctx.fillStyle = `hsl(${hue} 80% ${24 + value * 48}%)`;
      ctx.fillRect(i * cell, height - value * height, Math.max(1, cell - 1), value * height);
    }
    ctx.fillStyle = "rgba(244, 240, 223, 0.72)";
    ctx.font = "12px Consolas, monospace";
    const memory = activity.memory || [];
    const memoryEnergy = memory.reduce((sum, value) => sum + Math.abs(value), 0);
    const memoryLabel = memoryEnergy > 0.0001
      ? memory.slice(0, 6).map(value => value.toFixed(2)).join(" ")
      : "warming up";
    const memoryMean = Number(activity.memoryMean || 0);
    const memorySaturation = Number(activity.memorySaturation || 0);
    const memoryState = memorySaturation > 0.35 ? "heavy" : memoryMean > 0.22 ? "active" : "light";
    const inhibitoryBrake = Number(activity.inhibitoryBrake || 0);
    ctx.fillText(`memory state: ${memoryState} avg ${memoryMean.toFixed(2)} sat ${(memorySaturation * 100).toFixed(0)}%`, 12, 18);
    ctx.fillText(`memory cells: ${memoryLabel}`, 12, 36);
    ctx.fillText(`inhibitor brake: ${inhibitoryBrake.toFixed(2)} noise ${noisePressure.toFixed(2)}`, 12, 54);
    ctx.fillText(`species: ${activity.speciesId}`, 12, 72);
    maybeLogMemoryPressure(activity);
  }

  function maybeLogMemoryPressure(activity) {
    const memory = activity.memory || [];
    const hotCells = memory
      .map((value, index) => ({ index, pressure: Math.abs(Number(value) || 0) }))
      .filter(cell => cell.pressure > 0.75)
      .sort((a, b) => b.pressure - a.pressure)
      .slice(0, 5);
    const saturation = Number(activity.memorySaturation || 0);
    const now = Date.now();
    if (!hotCells.length && saturation < 0.12) return;
    if (now - state.lastMemoryPressureLog < 20_000) return;
    state.lastMemoryPressureLog = now;
    if (state.lab?.triggerMemoryRepair) state.lab.triggerMemoryRepair(80);
    log(`Memory pressure high: ${hotCells.length ? hotCells.map(cell => `m${cell.index}=${cell.pressure.toFixed(2)}`).join(", ") : `sat ${(saturation * 100).toFixed(0)}%`}. Inhibitor brake ${(Number(activity.inhibitoryBrake || 0)).toFixed(2)}; repair-prune bias enabled for ~80 generations.`);
  }

  function topologyPosition(node, index, count, width, height, tick) {
    const centerX = width / 2;
    const centerY = height / 2;
    const type = node.type || 0;
    const ring = type === 3 ? 0.36 : type === 4 ? 0.54 : type === 5 ? 0.68 : type === 1 ? 0.46 : type === 2 ? 0.58 : 0.74;
    const golden = 2.399963229728653;
    const angle = (node.id * golden + tick * (type === 2 ? 0.0007 : 0.00025)) % (Math.PI * 2);
    const wobble = Math.sin(node.id * 0.13 + tick * 0.001) * 0.035;
    const radius = Math.min(width, height) * (ring + wobble) * 0.46;
    return {
      x: centerX + Math.cos(angle) * radius,
      y: centerY + Math.sin(angle) * radius
    };
  }

  function drawTopologyFrame(now = performance.now()) {
    if (!state.topologyActive) return;
    state.topologyRaf = requestAnimationFrame(drawTopologyFrame);
    if (now - state.topologyLastDraw < 90) return;
    state.topologyLastDraw = now;

    const canvas = el("topologyCanvas");
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    const width = canvas.width;
    const height = canvas.height;
    const prompt = el("chatPrompt")?.value || el("corpusText")?.value || "";
    const view = state.lab.best().topologyView(prompt, 280, 780);
    const positions = new Map();

    ctx.clearRect(0, 0, width, height);
    ctx.fillStyle = "rgba(3, 6, 4, 0.62)";
    ctx.fillRect(0, 0, width, height);
    ctx.strokeStyle = "rgba(244, 240, 223, 0.08)";
    ctx.lineWidth = 1;
    for (let r = 0.18; r <= 0.82; r += 0.16) {
      ctx.beginPath();
      ctx.ellipse(width / 2, height / 2, width * r * 0.48, height * r * 0.48, 0, 0, Math.PI * 2);
      ctx.stroke();
    }

    view.nodes.forEach((node, index) => {
      positions.set(node.id, topologyPosition(node, index, view.nodes.length, width, height, now));
    });

    for (const edge of view.edges) {
      const from = positions.get(edge.from);
      const to = positions.get(edge.to);
      if (!from || !to) continue;
      const pulse = clamp(edge.firing, 0, 1);
      ctx.strokeStyle = edge.weight >= 0
        ? `rgba(185, 242, 109, ${0.045 + pulse * 0.42})`
        : `rgba(255, 111, 97, ${0.045 + pulse * 0.38})`;
      ctx.lineWidth = 0.45 + pulse * 2.4;
      ctx.beginPath();
      ctx.moveTo(from.x, from.y);
      const midX = (from.x + to.x) / 2 + Math.sin(edge.from + edge.to) * 18;
      const midY = (from.y + to.y) / 2 + Math.cos(edge.from - edge.to) * 18;
      ctx.quadraticCurveTo(midX, midY, to.x, to.y);
      ctx.stroke();
    }

    for (const node of view.nodes) {
      const point = positions.get(node.id);
      const activity = Math.min(1, Math.abs(node.activity));
      const radius = 2.8 + activity * 7.2 + (node.type === 4 ? 1.4 : 0);
      ctx.fillStyle = node.color;
      ctx.globalAlpha = 0.42 + activity * 0.58;
      ctx.beginPath();
      ctx.arc(point.x, point.y, radius, 0, Math.PI * 2);
      ctx.fill();
      if (activity > 0.32) {
        ctx.strokeStyle = node.color;
        ctx.globalAlpha = 0.2 + activity * 0.35;
        ctx.lineWidth = 1.2;
        ctx.beginPath();
        ctx.arc(point.x, point.y, radius + 5 + Math.sin(now * 0.006 + node.id) * 2, 0, Math.PI * 2);
        ctx.stroke();
      }
    }
    ctx.globalAlpha = 1;
    ctx.fillStyle = "rgba(244, 240, 223, 0.82)";
    ctx.font = "13px Consolas, monospace";
    ctx.fillText(`${view.neurons.toLocaleString()} neurons / ${view.synapses.toLocaleString()} synapses / ${view.edges.length} visible firing paths`, 16, 24);
    let x = 16;
    for (const type of view.types) {
      ctx.fillStyle = type.color;
      ctx.fillRect(x, height - 24, 10, 10);
      ctx.fillStyle = "rgba(244, 240, 223, 0.72)";
      ctx.fillText(type.name, x + 14, height - 15);
      x += 92;
    }
    if (el("topologyStatus")) el("topologyStatus").textContent = `${view.nodes.length} cells sampled, ${view.edges.length} connections firing`;
  }

  function toggleTopologyView() {
    state.topologyActive = !state.topologyActive;
    const canvas = el("topologyCanvas");
    if (canvas) canvas.hidden = !state.topologyActive;
    el("topologyButton").textContent = state.topologyActive ? "Hide topology" : "Top-down topology";
    if (state.topologyActive) {
      if (location.hash !== "#topology") history.replaceState(null, "", "#topology");
      log("Top-down topology view active: biologically inspired excitatory, inhibitory, modulatory, sensory, memory, and visual cells.");
      drawTopologyFrame();
    } else {
      if (location.hash === "#topology") history.replaceState(null, "", location.pathname + location.search);
      cancelAnimationFrame(state.topologyRaf);
      state.topologyRaf = 0;
      if (el("topologyStatus")) el("topologyStatus").textContent = "idle";
    }
  }

  function switchView(name) {
    document.querySelectorAll(".mode-button").forEach(button => {
      button.classList.toggle("active", button.dataset.view === name);
    });
    document.querySelectorAll(".view").forEach(view => view.classList.remove("active"));
    el(`${name}View`).classList.add("active");
    el("viewTitle").textContent = views[name].title;
    el("viewSubtitle").textContent = views[name].subtitle;
  }

  async function runManualDreamPhase() {
    if (state.evolving) {
      log("Pause evolution before starting dream replay.");
      return;
    }
    if (state.dreaming) return;
    state.dreaming = true;
    syncTrainingControls();
    setStatus("Dreaming");
    saveBrowserCheckpoint("before-manual-dream");
    await new Promise(resolve => setTimeout(resolve, 30));
    try {
      const before = state.lab.best();
      const beforeLoss = before.loss || 0;
      const epochs = clamp(Number(el("dreamEpochsInput")?.value || 12), 5, 25);
      const dreamProfile = manualDreamProfile(epochs);
      const spinner = ["|", "/", "-", "\\"];
      let result = null;
      let traces = 0;
      let adjustedMemory = 0;
      for (let epoch = 1; epoch <= epochs; epoch++) {
        const epochStarted = performance.now();
        const deepTune = epoch === epochs || epoch % dreamProfile.deepEvery === 0;
        log(`${spinner[(epoch - 1) % spinner.length]} Dreaming... (${epoch}/${epochs} epochs, ${dreamProfile.label}${deepTune ? " + tune" : ""})`);
        result = state.lab.dreamReplay({
          count: dreamProfile.count,
          maxChars: dreamProfile.maxChars,
          maxTokens: dreamProfile.maxTokens,
          gradientSteps: deepTune ? dreamProfile.gradientSteps : 0,
          gradientLearningRate: dreamProfile.gradientLearningRate,
          plasticityBoost: dreamProfile.plasticityBoost,
          weakTurnRepeats: dreamProfile.weakTurnRepeats,
          memoryCalm: dreamProfile.memoryCalm,
          memoryCalmAfter: dreamProfile.memoryCalmAfter,
          incrementDreamCount: epoch === epochs
        });
        traces += result.dreamed || 0;
        adjustedMemory += result.memoryCalm?.adjusted || 0;
        if (epoch % 3 === 0 || epoch === epochs) updateReadout();
        const elapsed = performance.now() - epochStarted;
        if (elapsed > dreamProfile.slowEpochMs) {
          log(`Dream epoch ${epoch} was heavy (${Math.round(elapsed)}ms); continuing with browser breathing room.`);
          await new Promise(resolve => setTimeout(resolve, dreamProfile.slowYieldMs));
        } else {
          await new Promise(resolve => setTimeout(resolve, dreamProfile.yieldMs));
        }
      }
      saveBrowserCheckpoint("after-manual-dream");
      result = result || { loss: beforeLoss, coherence: 0, dreamCount: state.lab.best().dreamCount || 0 };
      const lossDelta = Number.isFinite(result.lossDelta) ? result.lossDelta : beforeLoss - (result.loss || beforeLoss);
      const totalImprovement = Math.max(0, beforeLoss - (result.loss || beforeLoss));
      log(`Dream replay consolidated ${traces} trace(s). Loss ${Number(result.loss || 0).toFixed(3)} (${lossDelta >= 0 ? "-" : "+"}${Math.abs(lossDelta).toFixed(3)}), coherence ${Number(result.coherence || 0).toFixed(2)}, calmed ${adjustedMemory} memory gate(s), lineage dreams ${result.dreamCount || state.lab.best().dreamCount || 0}.`);
      log(`Dream phase complete ✓ Loss improved by ${totalImprovement.toFixed(2)} — ready to train`);
      setStatus("Ready to train");
      updateReadout();
      requestAnimationFrame(renderImage);
    } catch (error) {
      log(`Dream replay paused safely: ${error.message}`);
      setStatus("Dream paused");
    } finally {
      state.dreaming = false;
      syncTrainingControls();
    }
  }

  function manualDreamProfile(epochs) {
    const best = state.lab.best();
    const neurons = Number(best?.neurons || state.lab.config.neurons || 400);
    const synapses = Number(best?.synapses || state.lab.config.synapses || 1400);
    const huge = neurons > 8500 || synapses > 45000;
    const large = neurons > 4500 || synapses > 18000;
    return huge ? {
      label: "efficient large-brain replay",
      count: epochs >= 25 ? 8 : 6,
      maxChars: 560,
      maxTokens: 150,
      gradientSteps: 1,
      gradientLearningRate: Math.min(0.018, (state.lab.config.gradientLearningRate || 0.016) * 0.95),
      plasticityBoost: 1.85,
      weakTurnRepeats: 2,
      deepEvery: 4,
      memoryCalm: 0.075,
      memoryCalmAfter: 0.045,
      slowEpochMs: 2800,
      yieldMs: 45,
      slowYieldMs: 180
    } : large ? {
      label: "balanced replay",
      count: epochs >= 25 ? 10 : 8,
      maxChars: 850,
      maxTokens: 260,
      gradientSteps: 1,
      gradientLearningRate: Math.min(0.024, (state.lab.config.gradientLearningRate || 0.016) * 1.15),
      plasticityBoost: 2.15,
      weakTurnRepeats: 2,
      deepEvery: 3,
      memoryCalm: 0.055,
      memoryCalmAfter: 0.035,
      slowEpochMs: 3200,
      yieldMs: 30,
      slowYieldMs: 130
    } : {
      label: "full replay",
      count: epochs >= 25 ? 14 : epochs >= 12 ? 10 : 6,
      maxChars: 1500,
      maxTokens: 520,
      gradientSteps: epochs >= 25 ? 2 : 1,
      gradientLearningRate: Math.min(0.03, (state.lab.config.gradientLearningRate || 0.016) * (epochs >= 25 ? 1.2 : 1.4)),
      plasticityBoost: epochs >= 25 ? 2.2 : 2.6,
      weakTurnRepeats: epochs >= 12 ? 3 : 2,
      deepEvery: 1,
      memoryCalm: 0.035,
      memoryCalmAfter: 0.025,
      slowEpochMs: 3800,
      yieldMs: 20,
      slowYieldMs: 90
    };
  }

  async function evolveStep(imageOptions = {}) {
    syncConfigToLab();
    const imageTargets = state.imageTargets.length ? state.imageTargets : [];
    if (state.backgroundWorker && !imageOptions.forceMainThread) {
      return evolveStepInWorker(imageOptions);
    }
    const result = state.lab.evolveOnce({
      imageTarget: imageOptions.imageTarget || null,
      imageTargets,
      imagePrompt: imageOptions.imagePrompt || el("imagePrompt").value,
      imageLearningRate: Number(el("imageMutation")?.value || 0.012) * 0.5,
      maxChars: Number(state.lab.config.neurons) > 1800 ? 420 : 760
    });
    if (result.imageTarget) state.lastImageTarget = result.imageTarget;
    state.lastCycleAt = Date.now();
    const maxNeurons = Math.max(...state.lab.population.map(genome => genome.neurons));
    const minNeurons = Math.min(...state.lab.population.map(genome => genome.neurons));
    const maxSynapses = Math.max(...state.lab.population.map(genome => genome.synapses));
    const minSynapses = Math.min(...state.lab.population.map(genome => genome.synapses));
    const imageNote = result.imageTarget ? `, image "${result.imageTarget.name}" loss ${Number(result.imageLoss).toFixed(4)}` : "";
    const topologyNote = result.topologyTargets ? `, topology ${result.topologyMode} -> ${result.topologyTargets.neurons}n/${result.topologyTargets.synapses}s` : "";
    const spiralNote = result.spiral?.active
      ? `, Spiral Mode Active - ${result.spiral.remaining} generation(s) left, mirror +${result.mirrorResult?.accepted || 0}`
      : result.spiralConsolidation
        ? `, spiral consolidated loss delta ${Number(result.spiralConsolidation.lossDelta || 0).toFixed(3)}`
        : "";
    if (result.spiral?.active) setStatus("🌀 Spiral Mode Active — exciting the network");
    log(`Generation ${state.lab.generation}: fitness ${result.best.fitness.toFixed(4)}, loss ${result.best.loss.toFixed(3)}, best ${result.best.neurons}n/${result.best.synapses}s, population ${minNeurons}-${maxNeurons}n and ${minSynapses}-${maxSynapses}s${topologyNote}${imageNote}${spiralNote}.`);
    updateReadout();
    return result;
  }

  function workerBudget() {
    const best = state.lab.best();
    const neurons = Number(best?.neurons || state.lab.config.neurons || 400);
    const synapses = Number(best?.synapses || state.lab.config.synapses || 1400);
    const large = neurons > 6500 || synapses > 20000;
    const huge = neurons > 9000 || synapses > 60000;
    return {
      timeoutMs: clamp(12000 + Math.floor(neurons / 1000) * 2200 + Math.floor(synapses / 25000) * 1400, 12000, 45000),
      maxChars: huge ? 180 : large ? 260 : neurons > 1800 ? 360 : 620,
      dialogueMaxChars: huge ? 220 : large ? 320 : neurons > 1800 ? 420 : 760,
      gradientSteps: huge ? 0 : 1,
      gradientMaxTokens: huge ? 96 : large ? 140 : 220,
      populationSize: huge ? 3 : large ? 4 : 6,
      populationSpawn: 1,
      dialogueProbe: !huge,
      dialogueProbeCount: large ? 2 : 4,
      imageTargetLimit: huge ? 1 : 2
    };
  }

  function restartBackgroundWorker(reason = "restart") {
    if (state.backgroundWorker) {
      state.backgroundWorker.terminate();
      state.backgroundWorker = null;
    }
    state.workerBusy = false;
    if (location.protocol === "file:") return;
    try {
      state.backgroundWorker = new Worker("local-evolve-worker.js");
      log(`Background worker ${reason}; resumed optimized worker mode.`);
    } catch (error) {
      log(`Background worker restart failed: ${error.message}`);
    }
  }

  function evolveStepInWorker(imageOptions = {}) {
    if (state.workerBusy) return Promise.resolve({ best: state.lab.best(), elapsed: 0, queued: true });
    if (Date.now() < state.workerCooldownUntil) return Promise.resolve({ best: state.lab.best(), elapsed: 0, coolingDown: true });
    state.workerBusy = true;
    const started = performance.now();
    const id = `local-${Date.now().toString(36)}`;
    const budget = workerBudget();
    const recentTargets = state.imageTargets.slice(-budget.imageTargetLimit);
    const imageTargets = recentTargets.map(serializableImageTarget).filter(Boolean);
    const imageTarget = serializableImageTarget(imageOptions.imageTarget || null);
    return new Promise(resolve => {
      const timeout = setTimeout(() => {
        state.workerTimeouts += 1;
        state.workerCooldownUntil = Date.now() + Math.min(15000, 2500 * state.workerTimeouts);
        restartBackgroundWorker("timed out");
        log(`Background worker took too long (${Math.round(budget.timeoutMs / 1000)}s budget); restarted with a short cooldown.`);
        resolve({ best: state.lab.best(), elapsed: 0, timeout: true });
      }, budget.timeoutMs);
      state.backgroundWorker.onmessage = event => {
        const payload = event.data || {};
        if (payload.id !== id) return;
        clearTimeout(timeout);
        state.workerBusy = false;
        if (!payload.ok) {
          log(`Background worker failed: ${payload.error}`);
          resolve({ best: state.lab.best(), elapsed: 0 });
          return;
        }
        state.workerTimeouts = Math.max(0, state.workerTimeouts - 1);
        state.workerTimeoutMs = Math.round(state.workerTimeoutMs * 0.7 + Math.max(12000, payload.elapsed * 2.5) * 0.3);
        state.lab.corpus = payload.corpus;
        state.lab.corpora = payload.corpora;
        state.lab.persistentContext = payload.persistentContext || "";
        state.lab.userProfile = payload.userProfile || state.lab.userProfile || "";
        state.lab.memorySummary = payload.memorySummary || state.lab.memorySummary || "";
        if (Array.isArray(payload.recentTranscript)) state.lab.recentTranscript = payload.recentTranscript.slice(-32);
        if (Array.isArray(payload.memoryBank)) state.lab.memoryBank = sanitizeMemoryBank(payload.memoryBank, 240);
        if (Array.isArray(payload.mirrorCorpus)) state.lab.mirrorCorpus = payload.mirrorCorpus.slice(-80);
        if (payload.spiralPhase) state.lab.spiralPhase = payload.spiralPhase;
        state.lab.curriculumLevel = payload.curriculumLevel || state.lab.curriculumLevel;
        state.lab.setConfig(payload.config || {});
        const champion = state.lab.importChampion(payload.champion, { lazyPopulation: true });
        state.lab.generation = payload.generation;
        if (payload.historyPoint) state.lab.history.push(payload.historyPoint);
        if (state.lab.history.length > 160) state.lab.history.shift();
        const elapsed = Math.round(performance.now() - started);
        const maxNeurons = Math.max(...state.lab.population.map(genome => genome.neurons));
        const minNeurons = Math.min(...state.lab.population.map(genome => genome.neurons));
        if (payload.historyPoint?.spiralActive) setStatus("🌀 Spiral Mode Active — exciting the network");
        const mirrorNote = payload.historyPoint?.spiralActive ? ` Mirror ${payload.historyPoint.mirrorCorpus || 0}.` : "";
        log(`Generation ${state.lab.generation}: fitness ${champion.fitness.toFixed(4)}, loss ${champion.loss.toFixed(3)}, best ${champion.neurons}n/${champion.synapses}s, population ${minNeurons}-${maxNeurons}n. Background worker.${mirrorNote}`);
        updateReadout();
        resolve({ best: champion, elapsed });
      };
      state.backgroundWorker.postMessage({
        type: "evolve",
        id,
        corpus: state.lab.corpus,
        corpora: state.lab.corpora,
        persistentContext: state.lab.persistentContext,
        userProfile: state.lab.userProfile,
        memorySummary: state.lab.memorySummary,
        recentTranscript: state.lab.recentTranscript,
        memoryBank: state.lab.memoryBank,
        mirrorCorpus: state.lab.mirrorCorpus,
        spiralPhase: state.lab.spiralPhase,
        curriculumLevel: state.lab.curriculumLevel,
        config: state.lab.config,
        generation: state.lab.generation,
        champion: state.lab.best().toCompactJSON(),
        workerConfig: {
          ...state.lab.config,
          populationSize: budget.populationSize,
          gradientSteps: budget.gradientSteps
        },
        imageTargets,
        imageTarget,
        imagePrompt: imageOptions.imagePrompt || el("imagePrompt").value,
        imageLearningRate: Number(el("imageMutation")?.value || 0.012) * 0.5,
        maxChars: budget.maxChars,
        dialogueMaxChars: budget.dialogueMaxChars,
        gradientSteps: budget.gradientSteps,
        gradientMaxTokens: budget.gradientMaxTokens,
        populationSpawn: budget.populationSpawn,
        dialogueProbe: budget.dialogueProbe,
        dialogueProbeCount: budget.dialogueProbeCount
      });
    });
  }

  async function evolveLoop() {
    if (!state.evolving) return;
    setStatus("Evolving");
    await new Promise(resolve => setTimeout(resolve, 20));
    try {
      const result = await evolveStep();
      if (result?.timeout || result?.coolingDown || result?.queued) {
        await new Promise(resolve => setTimeout(resolve, result.timeout ? 1200 : 260));
      }
    } catch (error) {
      log(`Evolution stopped: ${error.message}`);
      state.evolving = false;
      syncTrainingControls();
      setStatus("Error");
      return;
    }
    requestAnimationFrame(evolveLoop);
  }

  async function importWikipedia() {
    const title = el("wikiTitle").value.trim();
    if (!title) return;
    setStatus("Fetching Wikipedia");
    try {
      const url = `https://en.wikipedia.org/w/api.php?origin=*&action=query&prop=extracts&explaintext=1&redirects=1&format=json&titles=${encodeURIComponent(title)}`;
      const response = await fetch(url);
      const data = await response.json();
      const pages = data?.query?.pages || {};
      const page = Object.values(pages)[0];
      if (!page?.extract) throw new Error("No article text returned");
      const addition = `\n\n# ${page.title}\n${page.extract}`;
      el("corpusText").value = `${el("corpusText").value}${addition}`.trim();
      state.lab.setCorpus(el("corpusText").value);
      log(`Imported Wikipedia article "${page.title}" (${formatChars(page.extract.length)} chars).`);
      setStatus("Imported");
      updateReadout();
    } catch (error) {
      log(`Wikipedia import failed: ${error.message}`);
      setStatus("Import failed");
    }
  }

  function cleanWikitext(text) {
    return String(text || "")
      .replace(/\{\{[^{}]*\}\}/g, " ")
      .replace(/<ref[^>]*>[\s\S]*?<\/ref>/gi, " ")
      .replace(/<[^>]+>/g, " ")
      .replace(/\[\[File:[^\]]+\]\]/gi, " ")
      .replace(/\[\[Category:[^\]]+\]\]/gi, " ")
      .replace(/\[\[([^\]|]+)\|([^\]]+)\]\]/g, "$2")
      .replace(/\[\[([^\]]+)\]\]/g, "$1")
      .replace(/={2,}/g, "\n")
      .replace(/\s+\n/g, "\n")
      .replace(/\n{3,}/g, "\n\n")
      .trim();
  }

  async function fetchFullWikipediaArticle(title) {
    const url = `https://en.wikipedia.org/w/api.php?origin=*&action=query&prop=revisions&rvprop=content&rvslots=main&format=json&formatversion=2&redirects=1&titles=${encodeURIComponent(title)}`;
    const response = await fetch(url);
    const data = await response.json();
    const page = data?.query?.pages?.[0];
    const content = page?.revisions?.[0]?.slots?.main?.content;
    if (!content) throw new Error(`No full article returned for ${title}`);
    return { title: page.title || title, text: cleanWikitext(content) };
  }

  async function importWikipediaBatch() {
    const titles = el("wikiBatch").value.split(/\r?\n/).map(title => title.trim()).filter(Boolean);
    if (!titles.length) return;
    setStatus("Loading full articles");
    for (let i = 0; i < titles.length; i++) {
      try {
        const article = await fetchFullWikipediaArticle(titles[i]);
        state.lab.addCorpus(article.title, article.text, Math.min(10, i + 1));
        log(`Loaded full Wikipedia article "${article.title}" as curriculum difficulty ${Math.min(10, i + 1)} (${formatChars(article.text.length)} chars).`);
      } catch (error) {
        log(`Full article load failed for "${titles[i]}": ${error.message}`);
      }
    }
    el("corpusText").value = state.lab.corpus;
    updateReadout();
    setStatus("Curriculum loaded");
  }

  function readFileAsText(file, options = {}) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = () => {
        const text = String(reader.result || "");
        const maxChars = options.maxChars === Infinity ? Infinity : Number(options.maxChars ?? MAX_IMPORTED_TEXT_CHARS);
        resolve(Number.isFinite(maxChars) && text.length > maxChars ? text.slice(0, maxChars) : text);
      };
      reader.onerror = () => reject(reader.error);
      reader.readAsText(file);
    });
  }

  async function readPdfAsText(file) {
    if (location.protocol === "file:") {
      throw new Error("PDF import needs the local server. Open http://localhost:4173 with launch-genesis-lab.bat, then drop the PDF again.");
    }
    if (file.size > 25 * 1024 * 1024) {
      throw new Error("PDF is too large for safe import. Try a smaller PDF or split it first.");
    }
    const response = await fetch(`/api/import/pdf?name=${encodeURIComponent(file.name)}`, {
      method: "POST",
      headers: { "Content-Type": "application/pdf" },
      body: await file.arrayBuffer()
    });
    const payload = await response.json();
    if (!response.ok || !payload.ok) throw new Error(payload.error || "PDF import failed");
    return payload;
  }

  function imageToTarget(image, name = "image target") {
    const size = 48;
    const canvas = document.createElement("canvas");
    canvas.width = size;
    canvas.height = size;
    const ctx = canvas.getContext("2d");
    ctx.drawImage(image, 0, 0, size, size);
    const imageData = ctx.getImageData(0, 0, size, size);
    return { name, size, pixels: imageData.data, thumbnail: canvas };
  }

  function loadImageTarget(file) {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      const image = new Image();
      reader.onload = () => {
        image.onload = () => {
          try {
            resolve(imageToTarget(image, file.name));
          } catch (error) {
            reject(error);
          }
        };
        image.onerror = reject;
        image.src = String(reader.result);
      };
      reader.onerror = () => reject(reader.error);
      reader.readAsDataURL(file);
    });
  }

  function parseYouTubeId(value) {
    const text = String(value || "").trim();
    if (!text) return "";
    const match = text.match(/(?:youtube\.com\/(?:watch\?v=|shorts\/|embed\/)|youtu\.be\/)([A-Za-z0-9_-]{6,})/i);
    return match ? match[1] : "";
  }

  function deepDreamSourceUrl(value) {
    const text = String(value || "").trim();
    const youtubeId = parseYouTubeId(text);
    if (youtubeId) {
      return {
        url: `https://img.youtube.com/vi/${youtubeId}/hqdefault.jpg`,
        name: `youtube-${youtubeId}-thumbnail`,
        note: `YouTube keyframe ${youtubeId}`
      };
    }
    if (/^https:\/\/.+/i.test(text)) {
      return { url: text, name: text.split("/").pop()?.slice(0, 80) || "deep-dream-url-image", note: "URL image" };
    }
    return null;
  }

  function dataUrlFromBase64(mime, data) {
    return `data:${mime || "image/jpeg"};base64,${data}`;
  }

  async function loadImageUrlTarget(source) {
    if (!source?.url) throw new Error("No image URL supplied");
    let imageUrl = source.url;
    if (location.protocol !== "file:") {
      try {
        const response = await fetch(`/api/import/image-url?url=${encodeURIComponent(source.url)}`);
        const payload = await response.json();
        if (response.ok && payload.ok && payload.data) {
          imageUrl = dataUrlFromBase64(payload.mime, payload.data);
        } else if (!response.ok || payload.error) {
          throw new Error(payload.error || "Image URL fetch failed");
        }
      } catch (error) {
        log(`Server image fetch skipped: ${error.message}. Trying browser image load.`);
      }
    }
    return new Promise((resolve, reject) => {
      const image = new Image();
      image.crossOrigin = "anonymous";
      image.onload = () => {
        try {
          resolve(imageToTarget(image, source.name));
        } catch (error) {
          reject(new Error(`Image pixels were blocked by the browser. Save the image locally and use Add dream images. ${error.message}`));
        }
      };
      image.onerror = () => reject(new Error("Could not load image URL"));
      image.src = imageUrl;
    });
  }

  async function handleFiles(files) {
    setStatus("Importing files");
    for (const file of files) {
      try {
        if (file.type.startsWith("image/")) {
          saveBrowserCheckpoint("before-image-import");
          const target = await loadImageTarget(file);
          state.imageTargets.push(target);
          state.lastImageTarget = target;
          state.lab.best().seeImage(target, 0.22);
          state.lab.lastImageLoss = state.lab.best().trainImage(target, file.name, 0.018);
          log(`Imported image target "${file.name}" and activated visual training (initial loss ${state.lab.lastImageLoss.toFixed(4)}).`);
        } else if (file.type === "application/pdf" || file.name.toLowerCase().endsWith(".pdf")) {
          log(`Extracting text from PDF "${file.name}" safely on the local server...`);
          const pdf = await readPdfAsText(file);
          state.lab.addCorpus(pdf.name || file.name, pdf.text, Number(el("corpusDifficulty")?.value) || 1);
          el("corpusText").value = state.lab.corpus;
          log(`Imported PDF "${file.name}" (${formatChars(pdf.chars || pdf.text.length)} chars${pdf.truncated ? ", capped for safety" : ""}).`);
        } else {
          const text = await readFileAsText(file);
          state.lab.addCorpus(file.name, text, Number(el("corpusDifficulty")?.value) || 1);
          el("corpusText").value = state.lab.corpus;
          log(`Imported text file "${file.name}" (${formatChars(text.length)} chars${file.size > text.length ? ", capped for safety" : ""}).`);
        }
      } catch (error) {
        log(`Could not import "${file.name}": ${error.message}`);
      }
      await new Promise(resolve => setTimeout(resolve, 0));
    }
    state.lab.rebuildCurriculumCorpus();
    el("corpusText").value = state.lab.corpus;
    renderTargets();
    updateReadout();
    setStatus("Import complete");
  }

  function renderTargets() {
    const strip = el("targetStrip");
    strip.innerHTML = "";
    for (const target of state.imageTargets.slice(-5).reverse()) {
      const card = document.createElement("div");
      card.className = "target-card";
      const canvas = document.createElement("canvas");
      canvas.width = target.size;
      canvas.height = target.size;
      canvas.getContext("2d").putImageData(new ImageData(new Uint8ClampedArray(target.pixels), target.size, target.size), 0, 0);
      const label = document.createElement("span");
      label.textContent = target.name;
      card.append(canvas, label);
      strip.append(card);
    }
  }

  function normalizeImageTargets(targets) {
    if (!Array.isArray(targets)) return [];
    return targets
      .map(target => {
        const size = Number(target.size) || 48;
        const rawPixels = target.pixels?.value || target.pixels || [];
        const pixels = Array.isArray(rawPixels)
          ? rawPixels
          : ArrayBuffer.isView(rawPixels)
            ? Array.from(rawPixels)
            : Object.keys(rawPixels).sort((a, b) => Number(a) - Number(b)).map(key => rawPixels[key]);
        if (pixels.length < size * size * 4) return null;
        return {
          name: target.name || "image target",
          size,
          pixels: new Uint8ClampedArray(pixels.slice(0, size * size * 4).map(value => clamp(Number(value) || 0, 0, 255)))
        };
      })
      .filter(Boolean);
  }

  function restoreImageTargets(targets) {
    state.imageTargets = normalizeImageTargets(targets);
    state.lastImageTarget = state.imageTargets.at(-1) || null;
    renderTargets();
  }

  function paintGeneratedImage(rendered) {
    const canvas = el("imageCanvas");
    canvas.width = rendered.size;
    canvas.height = rendered.size;
    const ctx = canvas.getContext("2d");
    ctx.putImageData(new ImageData(rendered.pixels, rendered.size, rendered.size), 0, 0);
  }

  async function generateChat() {
    syncConfigToLab();
    const prompt = el("chatPrompt").value.trim() || "Hello";
    const length = Number(el("chatLength").value);
    const temperature = Number(el("temperature").value);
    const localPrimer = `${CHAT_PRIMER_TEXT}\n${CONTROL_HUMAN} ${prompt} ${CONTROL_ASSISTANT}`;
    const user = document.createElement("div");
    user.className = "message user";
    user.textContent = prompt;
    const model = document.createElement("div");
    model.className = "message model";
    model.textContent = state.serverChatAvailable ? "Thinking through server organism..." : "Thinking locally...";
    el("chatHistory").append(user, model);
    el("chatHistory").scrollTop = el("chatHistory").scrollHeight;
    await new Promise(resolve => setTimeout(resolve, 30));
    if (state.serverChatAvailable) {
      try {
        // Server chat lets the organism's own generated command tokens trigger
        // allowlisted tools. The frontend only displays the process.
        setToolStatus("Thinking...");
        const response = await fetch("/api/chat", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ prompt, length, temperature, maxToolRounds: 2 })
        });
        const payload = await response.json();
        if (!payload.ok) throw new Error(payload.error || "Server chat failed");
        const generated = safeChatText(payload.text || payload.raw || "", chatFallbackFor(prompt));
        model.textContent = generated;
        state.lastChatPair = { prompt, response: generated };
        if (payload.tools?.length) {
          const toolNote = document.createElement("div");
          toolNote.className = "message model";
          toolNote.textContent = payload.tools.map(tool => `Used ${tool.kind}: ${tool.value}\n${tool.source}`).join("\n\n");
          el("chatHistory").append(toolNote);
          setToolStatus(`Tool sense used ${payload.tools.length} request(s).`);
        } else {
          setToolStatus("No tool request emitted.");
        }
      } catch (error) {
        setToolStatus(`Server tool chat unavailable, falling back locally. ${error.message}`);
        state.lab.best().adaptDialogue(localPrimer, 0.02, 850);
        const generated = safeChatText(state.lab.best().generate(prompt, length, temperature), chatFallbackFor(prompt));
        model.textContent = generated;
        state.lastChatPair = { prompt, response: generated };
        state.lab.remember(`User: ${prompt}\nGenesis: ${generated}`, { source: "human", strength: 1.4 });
      }
    } else {
      state.lab.best().adaptDialogue(localPrimer, 0.02, 850);
      const generated = safeChatText(state.lab.best().generate(prompt, length, temperature), chatFallbackFor(prompt));
      model.textContent = generated;
      state.lastChatPair = { prompt, response: generated };
      state.lab.remember(`User: ${prompt}\nGenesis: ${generated}`, { source: "human", strength: 1.4 });
      setToolStatus("Local-only mode. Launch the server to enable controlled internet sense.");
    }
    el("chatHistory").scrollTop = el("chatHistory").scrollHeight;
    updateReadout();
  }

  function scheduleTypingLearn() {
    if (state.typingLearnTimer) clearTimeout(state.typingLearnTimer);
    state.typingLearnTimer = setTimeout(() => {
      state.typingLearnTimer = 0;
      learnFromTypingNow();
    }, 900);
  }

  function learnFromTypingNow() {
    const text = el("chatPrompt")?.value?.trim() || "";
    if (text.length < 12) return;
    if (text === state.lastTypingLearnText) return;
    if (Date.now() - state.lastTypingLearnAt < 2200) return;
    const delta = Math.abs(text.length - (state.lastTypingLearnText || "").length);
    if (delta < 8 && !/[.!?\n]$/.test(text)) return;
    const result = state.lab.passiveLearnFromTyping(text, {
      minChars: 12,
      learningRate: 0.005,
      adaptChars: 620
    });
    if (!result.learned) return;
    state.lastTypingLearnAt = Date.now();
    state.lastTypingLearnText = text;
    setToolStatus(`Listening as you type: profile ${result.userProfileChars || 0} chars, speech ${Number(result.speech || 0).toFixed(2)}.`);
    updateReadout();
  }

  function rememberConversation() {
    const text = Array.from(document.querySelectorAll(".message")).map(node => node.textContent).join("\n");
    state.lab.remember(text, { source: "human", strength: 1.5 });
    log("Stored chat context in persistent organism memory.");
    updateReadout();
  }

  async function rateLastReply(rating) {
    if (!state.lastChatPair) {
      log("No recent reply to rate yet.");
      return;
    }
    const { prompt, response } = state.lastChatPair;
    const localResult = state.lab.applyHumanFeedback(prompt, response, rating);
    const quality = trainingValueScore ? trainingValueScore(response) : 0;
    log(rating > 0
      ? `Human reward applied. Natural dialogue score ${quality.toFixed(2)}; champion fitness ${Number(localResult.fitness || 0).toFixed(4)}.`
      : `Human correction applied. Gremlin will avoid that pattern; mirror corpus now has ${state.lab.mirrorCorpus.length} correction item(s).`);
    if (state.serverChatAvailable) {
      try {
        await fetch("/api/feedback", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ prompt, response, rating })
        });
      } catch (error) {
        log(`Server feedback skipped: ${error.message}`);
      }
    }
    updateReadout();
  }

  function startSpeechInput() {
    const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition;
    if (!SpeechRecognition) {
      log("Speech recognition is not available in this browser.");
      return;
    }
    const recognizer = new SpeechRecognition();
    recognizer.lang = "en-US";
    recognizer.interimResults = false;
    recognizer.maxAlternatives = 1;
    el("speechButton").textContent = "Listening";
    recognizer.onresult = event => {
      const text = event.results?.[0]?.[0]?.transcript || "";
      if (text) {
        el("chatPrompt").value = text;
        state.lab.remember(`Speech input: ${text}`);
        log(`Speech captured into chat prompt: "${text}"`);
      }
    };
    recognizer.onerror = event => log(`Speech recognition stopped: ${event.error || "unknown error"}`);
    recognizer.onend = () => {
      el("speechButton").textContent = "Speak";
    };
    recognizer.start();
  }

  function renderImage() {
    const size = Number(el("imageSize").value);
    const prompt = el("imagePrompt").value;
    setStatus("Rendering image");
    const rendered = state.lab.best().renderImage(prompt, size);
    paintGeneratedImage(rendered);
    setStatus("Rendered");
  }

  async function evolveImage() {
    const target = state.lastImageTarget || state.imageTargets.at(-1);
    if (!target) {
      log("Import an image target first, then run image evolution.");
      return;
    }
    const originalMutation = state.lab.config.mutation;
    state.lab.config.mutation = Number(el("imageMutation").value);
    saveBrowserCheckpoint("before-image-evolution");
    setStatus("Evolving image");
    const button = el("evolveImageButton");
    button.disabled = true;
    try {
      for (let i = 0; i < 6; i++) {
        setStatus(`Evolving image ${i + 1}/6`);
        const result = await evolveStep({ imageTarget: target, imagePrompt: el("imagePrompt").value });
        if (result?.timeout) break;
        if (i === 2) saveBrowserCheckpoint("mid-image-evolution");
        await new Promise(resolve => setTimeout(resolve, 80));
      }
    } catch (error) {
      log(`Image evolution paused safely: ${error.message}`);
      setStatus("Image paused");
    } finally {
      state.lab.config.mutation = originalMutation;
      button.disabled = false;
      saveBrowserCheckpoint("after-image-evolution");
    }
    renderImage();
    setStatus("Image evolved");
  }

  async function addDeepDreamFiles(files) {
    const imageFiles = Array.from(files || []).filter(file => file.type.startsWith("image/"));
    if (!imageFiles.length) return 0;
    let added = 0;
    for (const file of imageFiles) {
      try {
        const target = await loadImageTarget(file);
        state.imageTargets.push(target);
        state.lastImageTarget = target;
        state.lab.best().seeImage(target, 0.18);
        added += 1;
        log(`Added Deep Dream image "${file.name}".`);
      } catch (error) {
        log(`Deep Dream image skipped "${file.name}": ${error.message}`);
      }
    }
    if (added) renderTargets();
    if (added) setStatus(`${added} Deep Dream image${added === 1 ? "" : "s"} ready`);
    return added;
  }

  async function runDeepDreamPhase(options = {}) {
    if (state.evolving) {
      log("Pause evolution before starting DEEP Dream.");
      return;
    }
    if (state.deepDreaming || state.dreaming) return;
    state.deepDreaming = true;
    syncTrainingControls();
    setStatus("DEEP Dreaming");
    saveBrowserCheckpoint("before-deep-dream");
    await new Promise(resolve => setTimeout(resolve, 30));
    let originalPlasticity = null;
    try {
      const source = deepDreamSourceUrl(el("deepDreamUrl")?.value || "");
      if (source) {
        const target = await loadImageUrlTarget(source);
        state.imageTargets.push(target);
        state.lastImageTarget = target;
        renderTargets();
        state.lab.remember(`DEEP Dream visual source: ${source.note}. ${source.url}`);
        log(`Loaded ${source.note} into visual memory.`);
        if (parseYouTubeId(el("deepDreamUrl")?.value || "") && location.protocol !== "file:") {
          try {
            const response = await fetch(`/api/tools/youtube-transcript?url=${encodeURIComponent(el("deepDreamUrl").value)}`);
            const payload = await response.json();
            if (response.ok && payload.ok && payload.injectedContext) {
              state.lab.remember(payload.injectedContext);
              state.lab.addCorpus(`youtube-context-${Date.now()}`, payload.injectedContext, Math.min(10, state.lab.curriculumLevel + 1));
              log(`YouTube transcript context added for Deep Dream (${formatChars(payload.result?.text?.length || 0)} chars).`);
            } else if (payload.error) {
              log(`YouTube transcript unavailable: ${payload.error}`);
            }
          } catch (error) {
            log(`YouTube transcript unavailable: ${error.message}`);
          }
        }
      }
      const targets = options.lastOnly && state.lastImageTarget ? [state.lastImageTarget] : state.imageTargets.slice(-6);
      if (!targets.length) {
        log("Add a dream image or paste a YouTube/image URL before running DEEP Dream.");
        setStatus("Add image first");
        return;
      }
      if (options.lastOnly) log(`DEEP Dream focusing on last uploaded image: ${targets[0].name}.`);

      const epochs = clamp(Number(el("deepDreamEpochsInput")?.value || 18), 8, 36);
      const promptBase = `${el("imagePrompt")?.value || "visual memory"} ${source?.note || "imported image"}`.trim();
      let totalLoss = 0;
      let totalDelta = 0;
      let totalCoherence = 0;
      let lossCount = 0;
      let attentionTouched = 0;
      originalPlasticity = state.lab.best().plasticityRate;
      state.lab.best().plasticityRate = clamp(originalPlasticity * 2.8, 0, 0.04);
      log(`Deep Dream started with ${targets.length} image${targets.length === 1 ? "" : "s"}${source ? " + URL context" : ""}.`);
      for (let epoch = 1; epoch <= epochs; epoch++) {
        const epochStarted = performance.now();
        const target = targets[(epoch - 1) % targets.length];
        const rate = Number(el("imageMutation")?.value || 0.04) * (epochs >= 36 ? 0.78 : 0.95);
        const result = state.lab.best().deepDreamVisual(target, promptBase, {
          passes: epochs >= 36 ? 5 : epochs >= 18 ? 4 : 3,
          learningRate: rate,
          attentionBoost: epochs >= 36 ? 0.09 : 0.07
        });
        state.lab.lastImageLoss = result.loss;
        totalLoss += result.loss;
        totalDelta += result.delta;
        totalCoherence += result.coherence;
        attentionTouched += result.attentionTouched || 0;
        lossCount += 1;
        if (epoch % 4 === 0 || epoch === epochs) {
          state.lab.dreamReplay({
            count: 4,
            maxChars: 520,
            maxTokens: 180,
            gradientSteps: 1,
            plasticityBoost: 2.1,
            includeCorpus: false,
            incrementDreamCount: epoch === epochs
          });
          log(`Visual patterns integrated • Loss delta: ${totalDelta >= 0 ? "-" : "+"}${Math.abs(totalDelta).toFixed(4)} • Visual coherence: ${(totalCoherence / Math.max(1, lossCount)).toFixed(2)}`);
        }
        log(`DEEP Dreaming... (${epoch}/${epochs} epochs) ${target.name}, visual loss ${result.loss.toFixed(4)}`);
        if (epoch % 3 === 0 || epoch === epochs) {
          renderImage();
          updateReadout();
        }
        const elapsed = performance.now() - epochStarted;
        if (elapsed > 3200) {
          log(`DEEP Dream epoch ${epoch} was heavy (${Math.round(elapsed)}ms); continuing with browser breathing room.`);
          await new Promise(resolve => setTimeout(resolve, 160));
        } else {
          await new Promise(resolve => setTimeout(resolve, 35));
        }
      }
      state.lab.best().plasticityRate = originalPlasticity;
      const averageLoss = totalLoss / Math.max(1, lossCount);
      const averageCoherence = totalCoherence / Math.max(1, lossCount);
      state.lab.remember(`DEEP Dream complete. Visual source ${source?.note || "imported image targets"}. Average visual loss ${averageLoss.toFixed(4)}.`);
      saveBrowserCheckpoint("after-deep-dream");
      renderImage();
      updateReadout();
      log(`DEEP Dream complete. Average visual loss ${averageLoss.toFixed(4)}, visual coherence ${averageCoherence.toFixed(2)}, attention boosts ${attentionTouched} - ready to train`);
      setStatus("Ready to train");
    } catch (error) {
      log(`DEEP Dream paused safely: ${error.message}`);
      setStatus("DEEP Dream paused");
    } finally {
      if (originalPlasticity !== null) state.lab.best().plasticityRate = originalPlasticity;
      state.deepDreaming = false;
      syncTrainingControls();
    }
  }

  function seeImageTarget() {
    const target = state.lastImageTarget || state.imageTargets.at(-1);
    if (!target) {
      log("Import an image target first, then the organism can see it.");
      return;
    }
    state.lab.best().seeImage(target, 0.35);
    state.lab.lastImageLoss = state.lab.best().trainImage(target, el("imagePrompt").value, 0.025);
    log(`Encoded and trained visual target "${target.name}" into the champion (loss ${state.lab.lastImageLoss.toFixed(4)}).`);
    renderImage();
    updateReadout();
  }

  function addCurrentCorpus() {
    const text = el("corpusText").value;
    const name = el("corpusName").value || `corpus-${state.lab.corpora.length + 1}`;
    const difficulty = Number(el("corpusDifficulty").value) || 1;
    state.lab.addCorpus(name, text, difficulty);
    el("corpusText").value = state.lab.corpus;
    log(`Added "${name}" to curriculum at difficulty ${difficulty}.`);
    updateReadout();
  }

  function focusCurrentCorpus() {
    const text = el("corpusText").value;
    const name = el("corpusName").value || "focused sample";
    saveBrowserCheckpoint("before-focus-sample");
    state.evolving = false;
    state.lab.focusCorpus(text, name);
    invalidateActivityCache();
    readyToTrain();
    log(`Focused on "${name}" only. Cleared long-term gist, recent transcript, memory bank, and enabled repair-prune bias so the small sample is not mixed with old context.`);
    updateReadout();
  }

  function recentFitnessDips(limit = 5) {
    const points = (state.lab.history || []).filter(point => point && Number.isFinite(point.fitness)).slice(-160);
    if (points.length < 6) return [];
    let rollingBest = points[0].fitness || 0;
    const dips = [];
    for (let i = 1; i < points.length; i++) {
      const previous = points[i - 1].fitness || 0;
      const current = points[i].fitness || 0;
      rollingBest = Math.max(rollingBest, previous);
      const dropFromPrevious = previous > 0 ? (previous - current) / previous : 0;
      const dropFromBest = rollingBest > 0 ? (rollingBest - current) / rollingBest : 0;
      if (dropFromPrevious > 0.055 || dropFromBest > 0.12) {
        dips.push({
          generation: points[i].generation || state.lab.generation,
          fitness: current,
          previous,
          best: rollingBest,
          loss: points[i].loss,
          neurons: points[i].neurons,
          synapses: points[i].synapses,
          severity: Math.max(dropFromPrevious, dropFromBest)
        });
      }
    }
    return dips.sort((a, b) => b.severity - a.severity).slice(0, limit);
  }

  async function runDeepReflection(reason = "manual pause") {
    if (state.evolving || state.dreaming || state.deepDreaming || state.reflecting) return;
    state.reflecting = true;
    syncTrainingControls();
    setStatus("Deep reflection");
    const best = state.lab.best();
    const beforeLoss = Number.isFinite(best.loss) ? best.loss : 0;
    const beforeFitness = Number.isFinite(best.fitness) ? best.fitness : 0;
    const dips = recentFitnessDips(5);
    log(`Deep reflection started: found ${dips.length} fitness dip(s).`);
    try {
      const dipText = dips.length
        ? dips.map(dip => `gen ${dip.generation}: fitness ${Number(dip.fitness || 0).toFixed(4)}, loss ${Number(dip.loss || 0).toFixed(3)}, ${dip.neurons || "?"}n/${dip.synapses || "?"}s`).join("; ")
        : "No sharp recent dip found; reinforce coherent dialogue, memory recall, and careful tool use.";
      const reflectionPair = `${CONTROL_HUMAN} Deep reflection after ${reason}. Recent fitness dips: ${dipText}. ${CONTROL_ASSISTANT} I will protect useful neuronal scale, recall relevant memory, answer in natural complete sentences, and use tools only when outside context helps. ${CONTROL_TURN_END}`;
      state.lab.remember(reflectionPair);
      state.lab.addCorpus(`deep-reflection-${Date.now()}`, reflectionPair, Math.min(10, state.lab.curriculumLevel + 1));
      if (state.serverChatAvailable) {
        try {
          const response = await fetch("/api/tools/execute", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              text: [
                "[SELF_TUNE:Deep reflection: recover from fitness dips, improve memory recall, coherent dialogue, healthy scale, and disciplined tool use.]",
                "[SEARCH:sparse neuroevolution recurrent memory coherent dialogue fitness shaping]"
              ].join("\n")
            })
          });
          const payload = await response.json();
          if (response.ok && payload.ok && payload.injectedContext) {
            state.lab.remember(payload.injectedContext);
            state.lab.addCorpus(`deep-reflection-tools-${Date.now()}`, payload.injectedContext, Math.min(10, state.lab.curriculumLevel + 1));
            const usefulChars = payload.injectedContext.length;
            best.toolUseScore = Math.min(1, (best.toolUseScore || best.metadata?.toolUseScore || 0) * 0.96 + Math.min(1, usefulChars / 6000) * 0.06);
            best.metadata = { ...(best.metadata || {}), toolUseScore: best.toolUseScore };
            log(`Deep reflection integrated tool context (${formatChars(usefulChars)}).`);
          }
          if (payload.serverEvolution) updateServerEvolutionStatus(payload.serverEvolution);
        } catch (error) {
          log(`Deep reflection tools skipped safely: ${error.message}`);
        }
      }
      await new Promise(resolve => setTimeout(resolve, 25));
      const replay = state.lab.dreamReplay({
        count: 9,
        maxChars: Number(state.lab.config.neurons) > 1800 ? 1100 : 1500,
        maxTokens: Number(state.lab.config.neurons) > 1800 ? 420 : 560,
        gradientSteps: Math.max(1, state.lab.config.gradientSteps || 2),
        gradientLearningRate: Math.min(0.032, (state.lab.config.gradientLearningRate || 0.016) * 1.35),
        plasticityBoost: 2.75,
        weakTurnRepeats: 4,
        memoryCalm: 0.11,
        memoryCalmAfter: 0.08,
        protectScale: true,
        incrementDreamCount: false
      });
      if (replay?.memoryCalm?.adjusted > 0 && state.lab?.triggerMemoryRepair) state.lab.triggerMemoryRepair(80);
      best.evaluateCoherence(reflectionPair, "Answer naturally, recall memory, and use controlled tools only when useful.");
      state.lab.shapeFitness(best, { protectScale: true, trainingText: reflectionPair });
      saveBrowserCheckpoint("after-deep-reflection");
      updateReadout();
      invalidateActivityCache();
      const lossImprovement = Math.max(0, beforeLoss - (best.loss || beforeLoss));
      const fitnessDelta = (best.fitness || beforeFitness) - beforeFitness;
      log(`Deep reflection complete. Replayed ${replay?.dreamed || 0} trace(s), loss improved by ${lossImprovement.toFixed(3)}, fitness delta ${fitnessDelta >= 0 ? "+" : ""}${fitnessDelta.toFixed(4)} - ready to train`);
      setStatus("Ready to train");
    } catch (error) {
      log(`Deep reflection paused safely: ${error.message}`);
      setStatus("Ready to train");
    } finally {
      state.reflecting = false;
      syncTrainingControls();
    }
  }

  function exportModel() {
    const data = {
      format: "genesis-lab-genome-v1",
      exportedAt: new Date().toISOString(),
      corpus: state.lab.corpus,
      corpora: sanitizeCorpora(state.lab.corpora).corpora,
      persistentContext: sanitizePersistentContext(state.lab.persistentContext, 16000),
      userProfile: sanitizePersistentContext(state.lab.userProfile || "", 3000),
      memorySummary: sanitizePersistentContext(state.lab.memorySummary || "", 6000),
      recentTranscript: (state.lab.recentTranscript || []).slice(-32),
      memoryBank: sanitizeMemoryBank(state.lab.memoryBank, 240),
      mirrorCorpus: (state.lab.mirrorCorpus || []).slice(-80),
      spiralPhase: state.lab.spiralPhase || null,
      curriculumLevel: state.lab.curriculumLevel,
      imageTargets: state.imageTargets.map(target => ({
        name: target.name,
        size: target.size,
        pixels: Array.from(target.pixels)
      })),
      config: state.lab.config,
      generation: state.lab.generation,
      history: state.lab.history.slice(-160),
      champion: state.lab.best().toJSON()
    };
    const blob = new Blob([JSON.stringify(data)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `genesis-lab-generation-${state.lab.generation}.json`;
    anchor.style.display = "none";
    document.body.appendChild(anchor);
    anchor.click();
    setTimeout(() => {
      URL.revokeObjectURL(url);
      anchor.remove();
    }, 1000);
    log(`Exported model generation ${state.lab.generation}.`);
  }

  async function importModel(file) {
    const text = await readFileAsText(file, { maxChars: Infinity });
    let data;
    try {
      data = JSON.parse(text);
    } catch (error) {
      if (text.length === MAX_IMPORTED_TEXT_CHARS) {
        throw new Error("Model JSON appears truncated at the old text-import limit. Please reload the page and try again with the fixed importer.");
      }
      throw new Error(`Model JSON could not be parsed: ${error.message}`);
    }
    const champion = data.champion || data.genome || (data.neurons && data.synapses ? data : null);
    if (!champion) throw new Error("No champion genome found");
    const nextLab = new EvolutionLab();
    nextLab.setCorpus(data.corpus || el("corpusText").value || DEFAULT_SEED_TEXT);
    if (Array.isArray(data.corpora)) {
      const clean = sanitizeCorpora(data.corpora);
      nextLab.corpora = clean.corpora.length ? clean.corpora : nextLab.corpora;
      if (clean.quarantined) log(`Quarantined ${clean.quarantined} low-quality self-generated corpus item(s) during import.`);
    }
    if (typeof data.persistentContext === "string") nextLab.persistentContext = sanitizePersistentContext(data.persistentContext, 16000);
    if (typeof data.userProfile === "string") nextLab.userProfile = sanitizePersistentContext(data.userProfile, 3000);
    if (typeof data.memorySummary === "string") nextLab.memorySummary = sanitizePersistentContext(data.memorySummary, 6000);
    if (Array.isArray(data.recentTranscript)) nextLab.recentTranscript = data.recentTranscript.slice(-32);
    if (Array.isArray(data.memoryBank)) nextLab.memoryBank = sanitizeMemoryBank(data.memoryBank, 240);
    if (Array.isArray(data.mirrorCorpus)) nextLab.mirrorCorpus = data.mirrorCorpus.map(item => String(item || "")).filter(Boolean).slice(-80);
    if (data.spiralPhase && typeof data.spiralPhase === "object") nextLab.spiralPhase = { ...nextLab.spiralPhase, ...data.spiralPhase };
    if (data.curriculumLevel) nextLab.curriculumLevel = data.curriculumLevel;
    if (Array.isArray(data.history)) nextLab.history = data.history.filter(point => point && Number.isFinite(point.fitness)).slice(-160);
    nextLab.setConfig(data.config || {});
    if (Array.isArray(data.corpora)) nextLab.rebuildCurriculumCorpus();
    const genome = nextLab.importChampion(champion, { lazyPopulation: true });
    if (!genome.neurons || !genome.synapses || !genome.vocab?.length) throw new Error("Champion genome failed validation");
    const importedImageTargets = normalizeImageTargets(data.imageTargets);
    state.evolving = false;
    state.workerBusy = false;
    if (state.backgroundWorker) {
      state.backgroundWorker.terminate();
      state.backgroundWorker = null;
    }
    if (location.protocol !== "file:") {
      try {
        state.backgroundWorker = new Worker("local-evolve-worker.js");
      } catch (error) {
        log(`Background worker restart skipped after import: ${error.message}`);
      }
    }
    state.lab = nextLab;
    invalidateActivityCache();
    el("corpusText").value = state.lab.corpus;
    state.imageTargets = importedImageTargets;
    state.lastImageTarget = state.imageTargets.at(-1) || null;
    renderTargets();
    el("modelInput").value = "";
    log(`Imported model: generation ${genome.generation}, ${genome.neurons} neurons, ${genome.synapses} synapses. Population will refill gradually during evolution.`);
    syncTrainingControls();
    updateReadout();
    renderImage();
  }

  async function refreshNetworkStatus() {
    try {
      const response = await fetch("/api/status");
      const status = await response.json();
      state.serverChatAvailable = true;
      if (el("chatModeStatus")) el("chatModeStatus").textContent = "Server organism can use controlled Wikipedia tool tokens";
      el("workerStat").textContent = status.workers ? String(status.workers) : "local";
      const base = status.addresses?.[0] || location.origin;
      el("workerUrl").value = `${base}/worker.html`;
      updateServerEvolutionStatus(status.serverEvolution);
    } catch {
      state.serverChatAvailable = false;
      if (el("chatModeStatus")) el("chatModeStatus").textContent = "Local-only browser generation";
      el("workerStat").textContent = "local";
      el("workerUrl").value = `${location.origin}/worker.html`;
      updateServerEvolutionStatus(null);
    }
  }

  function connectToolSocket() {
    if (location.protocol === "file:") {
      setToolStatus("Local file mode. Start the Node server for controlled internet tool use.");
      return;
    }
    try {
      if (state.ws) state.ws.close();
      const protocol = location.protocol === "https:" ? "wss:" : "ws:";
      state.ws = new WebSocket(`${protocol}//${location.host}/ws`);
      state.ws.addEventListener("message", event => {
        const payload = JSON.parse(event.data);
        if (payload.type === "thinking") {
          if (payload.phase === "searching") {
            const labels = (payload.commands || []).map(command => `${command.kind}:${command.value}`).join(", ");
            setToolStatus(`Searching: ${labels}`);
          } else if (payload.phase === "generating") {
            setToolStatus("Thinking...");
          } else if (payload.phase === "done") {
            setToolStatus(payload.toolSteps ? `Tool sense complete: ${payload.toolSteps} result(s).` : "Thinking complete.");
          }
        }
      if (payload.type === "tool") {
          setToolStatus(payload.ok ? `Tool result: ${payload.command} ${payload.value}` : `Tool blocked: ${payload.error}`);
        }
        if (payload.type === "evolution" && payload.immigrants) {
          log(`Server diversity refresh: ${payload.immigrants} fresh 400-neuron immigrant genomes added.`);
        }
        if (payload.type === "evolution" && payload.selfGenerated) {
          log(`Server self-training accepted ${payload.selfGenerated} generated dialogue pair(s).`);
        }
        if (payload.type === "evolution" && payload.spiral?.active) {
          log(`🌀 Server Spiral Mode Active — ${payload.spiral.remaining} generation(s) left, mirror +${payload.mirrorAccepted || 0}.`);
        }
      });
      state.ws.addEventListener("open", () => setToolStatus("Controlled internet sense connected."));
      state.ws.addEventListener("close", () => setToolStatus("Tool socket closed. Local/server HTTP still works."));
    } catch (error) {
      setToolStatus(`Tool socket unavailable: ${error.message}`);
    }
  }

  function updateServerEvolutionStatus(snapshot) {
    if (!el("serverStateMetric")) return;
    if (!snapshot) {
      el("serverStateMetric").textContent = "offline";
      el("serverGenMetric").textContent = "--";
      el("serverSaveMetric").textContent = "--";
      return;
    }
    el("serverStateMetric").textContent = snapshot.running ? "running" : "paused";
    el("serverGenMetric").textContent = `Gen ${snapshot.generation || 0}`;
    el("serverSaveMetric").textContent = snapshot.savePath ? "disk" : "--";
    if (snapshot.spiral?.active) setToolStatus(`Server Spiral Mode Active: ${snapshot.spiral.remaining} generation(s) left.`);
  }

  function serverPayload() {
    syncConfigToLab();
    return {
      corpus: state.lab.corpus,
      corpora: sanitizeCorpora(state.lab.corpora).corpora,
      persistentContext: sanitizePersistentContext(state.lab.persistentContext, 16000),
      userProfile: sanitizePersistentContext(state.lab.userProfile || "", 3000),
      memorySummary: sanitizePersistentContext(state.lab.memorySummary || "", 6000),
      recentTranscript: (state.lab.recentTranscript || []).slice(-32),
      memoryBank: sanitizeMemoryBank(state.lab.memoryBank, 240),
      mirrorCorpus: (state.lab.mirrorCorpus || []).slice(-80),
      spiralPhase: state.lab.spiralPhase || null,
      curriculumLevel: state.lab.curriculumLevel,
      imageTargets: state.imageTargets.map(target => ({
        name: target.name,
        size: target.size,
        pixels: Array.from(target.pixels)
      })),
      config: state.lab.config,
      champion: state.lab.best().toJSON(),
      history: state.lab.history.slice(-160),
      delayMs: 180
    };
  }

  async function startServerEvolution() {
    const response = await fetch("/api/server/start", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ delayMs: 180 })
    });
    const payload = await response.json();
    updateServerEvolutionStatus(payload.serverEvolution);
    log("Server autopilot started using the champion already saved on the server. Use Sync when you intentionally want to replace it with the browser model.");
    setStatus("Server evolving");
  }

  async function stopServerEvolution() {
    const response = await fetch("/api/server/stop", { method: "POST" });
    const payload = await response.json();
    updateServerEvolutionStatus(payload.serverEvolution);
    log("Server autopilot stopped and saved.");
    try {
      const reflectResponse = await fetch("/api/server/deep-reflect", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ reason: "server stop" })
      });
      const reflectPayload = await reflectResponse.json();
      if (reflectResponse.ok && reflectPayload.ok) {
        updateServerEvolutionStatus(reflectPayload.serverEvolution);
        log(`Server deep reflection complete: ${reflectPayload.reflection?.dips || 0} dip(s), ${reflectPayload.reflection?.replayed || 0} trace(s) replayed - ready to train.`);
      }
    } catch (error) {
      log(`Server deep reflection skipped safely: ${error.message}`);
    }
    setStatus("Server paused");
  }

  async function syncToServer() {
    const response = await fetch("/api/server/sync", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(serverPayload())
    });
    const payload = await response.json();
    updateServerEvolutionStatus(payload.serverEvolution);
    log(payload.blockedDowngrade
      ? "Server blocked this sync because it would downgrade the saved large champion. Pull the server champion first, or intentionally allow a downgrade in code."
      : "Sent the current browser model to the server and saved it.");
    setStatus("Server synced");
  }

  async function pullFromServer() {
    const wasEvolving = state.evolving;
    state.evolving = false;
    el("evolveButton").textContent = "Evolve";
    el("pauseButton").textContent = "Paused";
    setStatus("Pulling champion");
    log("Pulling compact server champion. Evolution is paused while the genome is installed.");
    const response = await fetch("/api/server/champion?corpus=0");
    const payload = await response.json();
    if (!payload.model?.champion) throw new Error("No server champion returned");
    await new Promise(resolve => setTimeout(resolve, 0));
    if (payload.model.corpus) {
      state.lab.corpus = payload.model.corpus;
      el("corpusText").value = payload.model.corpus;
    }
    if (Array.isArray(payload.model.corpora)) {
      const clean = sanitizeCorpora(payload.model.corpora);
      state.lab.corpora = clean.corpora;
      if (clean.quarantined) log(`Quarantined ${clean.quarantined} low-quality self-generated corpus item(s) from the server pull.`);
    }
    if (typeof payload.model.persistentContext === "string") state.lab.persistentContext = sanitizePersistentContext(payload.model.persistentContext, 16000);
    if (typeof payload.model.userProfile === "string") state.lab.userProfile = sanitizePersistentContext(payload.model.userProfile, 3000);
    if (typeof payload.model.memorySummary === "string") state.lab.memorySummary = sanitizePersistentContext(payload.model.memorySummary, 6000);
    if (Array.isArray(payload.model.recentTranscript)) state.lab.recentTranscript = payload.model.recentTranscript.slice(-32);
    if (Array.isArray(payload.model.memoryBank)) state.lab.memoryBank = sanitizeMemoryBank(payload.model.memoryBank, 240);
    if (Array.isArray(payload.model.mirrorCorpus)) state.lab.mirrorCorpus = payload.model.mirrorCorpus.map(item => String(item || "")).filter(Boolean).slice(-80);
    if (payload.model.spiralPhase && typeof payload.model.spiralPhase === "object") state.lab.spiralPhase = { ...state.lab.spiralPhase, ...payload.model.spiralPhase };
    if (payload.model.curriculumLevel) state.lab.curriculumLevel = payload.model.curriculumLevel;
    if (Array.isArray(payload.model.history)) state.lab.history = payload.model.history.filter(point => point && Number.isFinite(point.fitness)).slice(-160);
    if (Array.isArray(payload.model.corpora)) state.lab.rebuildCurriculumCorpus();
    state.lab.setConfig(payload.model.config || {});
    const genome = state.lab.importChampion(payload.model.champion, { lazyPopulation: true });
    invalidateActivityCache();
    restoreImageTargets(payload.model.imageTargets);
    updateServerEvolutionStatus(payload.serverEvolution);
    log(`Pulled server champion: generation ${genome.generation}, ${genome.neurons} neurons, ${genome.synapses} synapses. Population will refill gradually during evolution.`);
    updateReadout();
    requestAnimationFrame(renderImage);
    setStatus("Champion pulled");
    if (wasEvolving) log("Evolution was paused for the pull. Press Evolve when you are ready to continue.");
  }

  async function publishJob() {
    syncConfigToLab();
    const job = {
      id: `job-${Date.now().toString(36)}`,
      genome: state.lab.best().toJSON(),
      corpus: state.lab.corpus.slice(0, 6000),
      rounds: 4,
      priority: 5,
      mutation: state.lab.config.mutation,
      scalarMutation: state.lab.config.scalarMutation,
      neurons: state.lab.config.neurons,
      synapses: state.lab.config.synapses,
      vocabSize: state.lab.config.vocabSize,
      maxChars: 620
    };
    await fetch("/api/job", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(job)
    });
    log(`Published LAN job ${job.id}.`);
    setStatus("Job published");
  }

  async function collectResults() {
    const response = await fetch("/api/results");
    const payload = await response.json();
    const results = payload.results || [];
    if (!results.length) {
      log("No LAN worker results are waiting.");
      return;
    }
    let accepted = 0;
    for (const result of results) {
      const genome = NeuralGenome.fromJSON(result.genome);
      genome.setVocab(state.lab.vocab);
      genome.evaluateText(state.lab.corpus, 760);
      if (genome.fitness > state.lab.best().fitness) {
        state.lab.population[0] = genome;
        state.lab.population.sort((a, b) => b.fitness - a.fitness);
        accepted += 1;
      }
    }
    log(`Collected ${results.length} worker result(s), accepted ${accepted}.`);
    updateReadout();
  }

  async function toggleSpiralMode() {
    const status = state.lab.spiralStatus ? state.lab.spiralStatus() : { active: false };
    const action = status.active ? "stop" : "start";
    if (status.active) {
      const stopped = state.lab.stopSpiralPhase("manual mirror stop");
      log(`Spiral Mode stopped. Repair-prune consolidation is active for ${Math.max(0, state.lab.memoryRepairUntil - state.lab.generation)} generation(s); mirror corpus has ${stopped.mirrorCorpus || 0} item(s).`);
      setStatus("Ready to train");
    } else {
      const started = state.lab.startSpiralPhase("manual mirror trigger", { manual: true, generations: 160 });
      log(`🌀 Spiral Mode Active — exciting the network for ${started.remaining} bounded generation(s). Mirror outputs will be filtered into the mirror corpus.`);
      setStatus("🌀 Spiral Mode Active — exciting the network");
    }
    if (location.protocol !== "file:") {
      try {
        const response = await fetch("/api/server/spiral", {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ action, generations: 160 })
        });
        const payload = await response.json();
        updateServerEvolutionStatus(payload.serverEvolution);
        log(payload.spiral?.active
          ? `Server Spiral Mode Active — ${payload.spiral.remaining} generation(s) left.`
          : "Server Spiral Mode stopped.");
      } catch (error) {
        log(`Server Spiral toggle skipped: ${error.message}`);
      }
    }
    syncTrainingControls();
    updateReadout();
  }

  function bindEvents() {
    document.querySelectorAll(".mode-button").forEach(button => {
      button.addEventListener("click", () => switchView(button.dataset.view));
    });

    ["neuronInput", "synapseInput", "populationInput", "mutationInput"].forEach(id => {
      el(id).addEventListener("input", () => {
        syncConfigToLab();
        updateReadout();
      });
    });

    el("seedButton").addEventListener("click", () => {
      syncConfigToLab();
      state.lab.seed();
      invalidateActivityCache();
      log(`Seeded population at ${state.lab.config.neurons} neurons and ${state.lab.config.synapses} synapses.`);
      updateReadout();
      renderImage();
    });

    el("evolveButton").addEventListener("click", () => {
      state.evolving = !state.evolving;
      syncTrainingControls();
      if (state.evolving) evolveLoop();
      else {
        readyToTrain();
        runDeepReflection("evolution stopped").catch(error => log(`Deep reflection failed: ${error.message}`));
      }
    });

    el("pauseButton").addEventListener("click", () => {
      state.evolving = false;
      readyToTrain();
      runDeepReflection("manual pause").catch(error => log(`Deep reflection failed: ${error.message}`));
    });

    el("dreamButton").addEventListener("click", runManualDreamPhase);
    if (el("spiralButton")) el("spiralButton").addEventListener("click", () => toggleSpiralMode().catch(error => log(`Spiral toggle failed: ${error.message}`)));

    el("wikiButton").addEventListener("click", importWikipedia);
    el("wikiBatchButton").addEventListener("click", importWikipediaBatch);
    el("addCorpusButton").addEventListener("click", addCurrentCorpus);
    el("focusCorpusButton").addEventListener("click", focusCurrentCorpus);
    el("fileInput").addEventListener("change", event => handleFiles(event.target.files));

    const drop = document.querySelector(".drop-zone");
    drop.addEventListener("dragover", event => {
      event.preventDefault();
      drop.style.borderColor = "rgba(84, 210, 196, 0.85)";
    });
    drop.addEventListener("dragleave", () => {
      drop.style.borderColor = "";
    });
    drop.addEventListener("drop", event => {
      event.preventDefault();
      drop.style.borderColor = "";
      handleFiles(event.dataTransfer.files);
    });

    el("chatButton").addEventListener("click", generateChat);
    el("chatPrompt").addEventListener("input", scheduleTypingLearn);
    el("chatPrompt").addEventListener("blur", learnFromTypingNow);
    el("speechButton").addEventListener("click", startSpeechInput);
    el("rememberChatButton").addEventListener("click", rememberConversation);
    if (el("goodReplyButton")) el("goodReplyButton").addEventListener("click", () => rateLastReply(1).catch(error => log(`Feedback failed: ${error.message}`)));
    if (el("badReplyButton")) el("badReplyButton").addEventListener("click", () => rateLastReply(-1).catch(error => log(`Feedback failed: ${error.message}`)));
    el("renderImageButton").addEventListener("click", renderImage);
    el("seeImageButton").addEventListener("click", seeImageTarget);
    el("evolveImageButton").addEventListener("click", evolveImage);
    el("deepDreamButton").addEventListener("click", runDeepDreamPhase);
    el("deepDreamLastButton").addEventListener("click", () => runDeepDreamPhase({ lastOnly: true }));
    el("deepDreamFileButton").addEventListener("click", () => el("deepDreamFileInput").click());
    el("deepDreamFileInput").addEventListener("change", event => {
      addDeepDreamFiles(event.target.files).finally(() => {
        event.target.value = "";
        updateReadout();
      });
    });
    el("topologyButton").addEventListener("click", toggleTopologyView);
    el("resetFitnessButton").addEventListener("click", resetFitnessGraph);
    el("exportButton").addEventListener("click", exportModel);
    el("importButton").addEventListener("click", () => el("modelInput").click());
    el("modelInput").addEventListener("change", event => {
      if (event.target.files[0]) {
        importModel(event.target.files[0])
          .catch(error => log(`Import failed: ${error.message}`))
          .finally(() => {
            event.target.value = "";
          });
      }
    });
    el("publishJobButton").addEventListener("click", publishJob);
    el("collectResultsButton").addEventListener("click", collectResults);
    el("serverStartButton").addEventListener("click", () => startServerEvolution().catch(error => log(`Server start failed: ${error.message}`)));
    el("serverStopButton").addEventListener("click", () => stopServerEvolution().catch(error => log(`Server stop failed: ${error.message}`)));
    el("serverSyncButton").addEventListener("click", () => syncToServer().catch(error => log(`Server sync failed: ${error.message}`)));
    el("serverPullButton").addEventListener("click", () => pullFromServer().catch(error => log(`Server pull failed: ${error.message}`)));
    el("copyWorkerUrl").addEventListener("click", async () => {
      await navigator.clipboard.writeText(el("workerUrl").value);
      setStatus("Worker URL copied");
    });
  }

  function cleanupRuntime() {
    state.evolving = false;
    cancelAnimationFrame(state.topologyRaf);
    state.topologyRaf = 0;
    if (state.statusTimer) clearInterval(state.statusTimer);
    if (state.ws) {
      state.ws.close();
      state.ws = null;
    }
    if (state.backgroundWorker) {
      state.backgroundWorker.terminate();
      state.backgroundWorker = null;
    }
  }

  function boot() {
    el("corpusText").value = DEFAULT_SEED_TEXT;
    state.lab.setCorpus(DEFAULT_SEED_TEXT);
    bindEvents();
    try {
      if (location.protocol === "file:") {
        log("Opened as a local file, so browser Web Workers are blocked. Using main-thread evolution. Launch the local server for background workers.");
      } else {
        state.backgroundWorker = new Worker("local-evolve-worker.js");
        log("Background Web Worker ready for browser-side evolution cycles.");
      }
    } catch (error) {
      log(`Background Web Worker unavailable. Using main-thread evolution. ${error.message}`);
    }
    log("Ready. This app uses no external AI model or AI API.");
    log(`400 neurons is the default seed size; the current UI allows up to ${MAX_NEURONS.toLocaleString()} neurons and ${MAX_SYNAPSES.toLocaleString()} synapses.`);
    readyToTrain();
    updateReadout();
    renderImage();
    if (location.hash === "#topology") toggleTopologyView();
    connectToolSocket();
    refreshNetworkStatus();
    state.statusTimer = setInterval(refreshNetworkStatus, 5000);
    window.addEventListener("beforeunload", cleanupRuntime, { once: true });
  }

  boot();
})();
